// Code generated by protoc-gen-go.
// source: api/list_problems.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ListProblemsRequest_Element int32

const (
	ListProblemsRequest_PID     ListProblemsRequest_Element = 0
	ListProblemsRequest_TITLE   ListProblemsRequest_Element = 1
	ListProblemsRequest_AC_RATE ListProblemsRequest_Element = 2
)

var ListProblemsRequest_Element_name = map[int32]string{
	0: "PID",
	1: "TITLE",
	2: "AC_RATE",
}
var ListProblemsRequest_Element_value = map[string]int32{
	"PID":     0,
	"TITLE":   1,
	"AC_RATE": 2,
}

func (x ListProblemsRequest_Element) String() string {
	return proto.EnumName(ListProblemsRequest_Element_name, int32(x))
}
func (ListProblemsRequest_Element) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{0, 0}
}

type ListProblemsRequest_Filter_ProblemStatus int32

const (
	ListProblemsRequest_Filter_ALL       ListProblemsRequest_Filter_ProblemStatus = 0
	ListProblemsRequest_Filter_ACCEPTED  ListProblemsRequest_Filter_ProblemStatus = 1
	ListProblemsRequest_Filter_UNSOLVED  ListProblemsRequest_Filter_ProblemStatus = 2
	ListProblemsRequest_Filter_ATTEMPTED ListProblemsRequest_Filter_ProblemStatus = 3
)

var ListProblemsRequest_Filter_ProblemStatus_name = map[int32]string{
	0: "ALL",
	1: "ACCEPTED",
	2: "UNSOLVED",
	3: "ATTEMPTED",
}
var ListProblemsRequest_Filter_ProblemStatus_value = map[string]int32{
	"ALL":       0,
	"ACCEPTED":  1,
	"UNSOLVED":  2,
	"ATTEMPTED": 3,
}

func (x ListProblemsRequest_Filter_ProblemStatus) String() string {
	return proto.EnumName(ListProblemsRequest_Filter_ProblemStatus_name, int32(x))
}
func (ListProblemsRequest_Filter_ProblemStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor4, []int{0, 0, 0}
}

type ListProblemsRequest struct {
	Offset      int32                       `protobuf:"varint,1,opt,name=offset" json:"offset,omitempty"`
	PerPage     int32                       `protobuf:"varint,2,opt,name=per_page,json=perPage" json:"per_page,omitempty"`
	CurrentPage int32                       `protobuf:"varint,3,opt,name=current_page,json=currentPage" json:"current_page,omitempty"`
	OrderBy     ListProblemsRequest_Element `protobuf:"varint,4,opt,name=order_by,json=orderBy,enum=api.ListProblemsRequest_Element" json:"order_by,omitempty"`
	IsDesc      bool                        `protobuf:"varint,5,opt,name=is_desc,json=isDesc" json:"is_desc,omitempty"`
	Filter      *ListProblemsRequest_Filter `protobuf:"bytes,6,opt,name=filter" json:"filter,omitempty"`
}

func (m *ListProblemsRequest) Reset()                    { *m = ListProblemsRequest{} }
func (m *ListProblemsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListProblemsRequest) ProtoMessage()               {}
func (*ListProblemsRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *ListProblemsRequest) GetOffset() int32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListProblemsRequest) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *ListProblemsRequest) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *ListProblemsRequest) GetOrderBy() ListProblemsRequest_Element {
	if m != nil {
		return m.OrderBy
	}
	return ListProblemsRequest_PID
}

func (m *ListProblemsRequest) GetIsDesc() bool {
	if m != nil {
		return m.IsDesc
	}
	return false
}

func (m *ListProblemsRequest) GetFilter() *ListProblemsRequest_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

type ListProblemsRequest_Filter struct {
	Oj      string                                   `protobuf:"bytes,1,opt,name=oj" json:"oj,omitempty"`
	PStatus ListProblemsRequest_Filter_ProblemStatus `protobuf:"varint,2,opt,name=p_status,json=pStatus,enum=api.ListProblemsRequest_Filter_ProblemStatus" json:"p_status,omitempty"`
}

func (m *ListProblemsRequest_Filter) Reset()                    { *m = ListProblemsRequest_Filter{} }
func (m *ListProblemsRequest_Filter) String() string            { return proto.CompactTextString(m) }
func (*ListProblemsRequest_Filter) ProtoMessage()               {}
func (*ListProblemsRequest_Filter) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0, 0} }

func (m *ListProblemsRequest_Filter) GetOj() string {
	if m != nil {
		return m.Oj
	}
	return ""
}

func (m *ListProblemsRequest_Filter) GetPStatus() ListProblemsRequest_Filter_ProblemStatus {
	if m != nil {
		return m.PStatus
	}
	return ListProblemsRequest_Filter_ALL
}

type ListProblemsResponse struct {
	Lines       []*ListProblemsResponse_PerLine `protobuf:"bytes,1,rep,name=lines" json:"lines,omitempty"`
	TotalLines  int32                           `protobuf:"varint,2,opt,name=total_lines,json=totalLines" json:"total_lines,omitempty"`
	TotalPages  int32                           `protobuf:"varint,3,opt,name=total_pages,json=totalPages" json:"total_pages,omitempty"`
	CurrentPage int32                           `protobuf:"varint,4,opt,name=current_page,json=currentPage" json:"current_page,omitempty"`
	Error       *Error                          `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
}

func (m *ListProblemsResponse) Reset()                    { *m = ListProblemsResponse{} }
func (m *ListProblemsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListProblemsResponse) ProtoMessage()               {}
func (*ListProblemsResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *ListProblemsResponse) GetLines() []*ListProblemsResponse_PerLine {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *ListProblemsResponse) GetTotalLines() int32 {
	if m != nil {
		return m.TotalLines
	}
	return 0
}

func (m *ListProblemsResponse) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *ListProblemsResponse) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *ListProblemsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ListProblemsResponse_PerLine struct {
	Sid             string `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
	Oj              string `protobuf:"bytes,2,opt,name=oj" json:"oj,omitempty"`
	Pid             string `protobuf:"bytes,3,opt,name=pid" json:"pid,omitempty"`
	Title           string `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	Source          string `protobuf:"bytes,5,opt,name=source" json:"source,omitempty"`
	AcSubmission    int32  `protobuf:"varint,6,opt,name=ac_submission,json=acSubmission" json:"ac_submission,omitempty"`
	TotalSubmission int32  `protobuf:"varint,7,opt,name=total_submission,json=totalSubmission" json:"total_submission,omitempty"`
}

func (m *ListProblemsResponse_PerLine) Reset()                    { *m = ListProblemsResponse_PerLine{} }
func (m *ListProblemsResponse_PerLine) String() string            { return proto.CompactTextString(m) }
func (*ListProblemsResponse_PerLine) ProtoMessage()               {}
func (*ListProblemsResponse_PerLine) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1, 0} }

func (m *ListProblemsResponse_PerLine) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *ListProblemsResponse_PerLine) GetOj() string {
	if m != nil {
		return m.Oj
	}
	return ""
}

func (m *ListProblemsResponse_PerLine) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *ListProblemsResponse_PerLine) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *ListProblemsResponse_PerLine) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *ListProblemsResponse_PerLine) GetAcSubmission() int32 {
	if m != nil {
		return m.AcSubmission
	}
	return 0
}

func (m *ListProblemsResponse_PerLine) GetTotalSubmission() int32 {
	if m != nil {
		return m.TotalSubmission
	}
	return 0
}

func init() {
	proto.RegisterType((*ListProblemsRequest)(nil), "api.ListProblemsRequest")
	proto.RegisterType((*ListProblemsRequest_Filter)(nil), "api.ListProblemsRequest.Filter")
	proto.RegisterType((*ListProblemsResponse)(nil), "api.ListProblemsResponse")
	proto.RegisterType((*ListProblemsResponse_PerLine)(nil), "api.ListProblemsResponse.PerLine")
	proto.RegisterEnum("api.ListProblemsRequest_Element", ListProblemsRequest_Element_name, ListProblemsRequest_Element_value)
	proto.RegisterEnum("api.ListProblemsRequest_Filter_ProblemStatus", ListProblemsRequest_Filter_ProblemStatus_name, ListProblemsRequest_Filter_ProblemStatus_value)
}

func init() { proto.RegisterFile("api/list_problems.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 539 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x53, 0xc1, 0x6e, 0xd3, 0x4a,
	0x14, 0xad, 0xed, 0xda, 0x8e, 0xaf, 0xdb, 0x3c, 0x6b, 0x5e, 0x45, 0x4d, 0x36, 0x75, 0xc3, 0x26,
	0x20, 0x61, 0xa4, 0xb0, 0xe8, 0x82, 0x55, 0x48, 0x8c, 0xa8, 0x64, 0x20, 0x9a, 0x18, 0xb6, 0x96,
	0xe3, 0x4c, 0xaa, 0xa9, 0x1c, 0xcf, 0x30, 0x33, 0x59, 0xf4, 0x3f, 0xf8, 0x07, 0x3e, 0x82, 0x9f,
	0xe0, 0x93, 0x90, 0x67, 0xac, 0x42, 0xd4, 0x22, 0x76, 0x73, 0xcf, 0x39, 0x77, 0xe6, 0x5c, 0x9f,
	0x6b, 0x38, 0xaf, 0x38, 0x7d, 0xd5, 0x50, 0xa9, 0x4a, 0x2e, 0xd8, 0xba, 0x21, 0x3b, 0x99, 0x72,
	0xc1, 0x14, 0x43, 0x4e, 0xc5, 0xe9, 0x28, 0xea, 0xd8, 0x9a, 0xed, 0x76, 0xac, 0x35, 0xf0, 0xf8,
	0xa7, 0x03, 0xff, 0xe7, 0x54, 0xaa, 0x65, 0xaf, 0xc6, 0xe4, 0xeb, 0x9e, 0x48, 0x85, 0x9e, 0x80,
	0xc7, 0xb6, 0x5b, 0x49, 0x54, 0x6c, 0x25, 0xd6, 0xc4, 0xc5, 0x7d, 0x85, 0x9e, 0xc2, 0x80, 0x13,
	0x51, 0xf2, 0xea, 0x86, 0xc4, 0xb6, 0x66, 0x7c, 0x4e, 0xc4, 0xb2, 0xba, 0x21, 0xe8, 0x12, 0x4e,
	0xea, 0xbd, 0x10, 0xa4, 0x55, 0x86, 0x76, 0x34, 0x1d, 0xf6, 0x98, 0x96, 0xbc, 0x81, 0x01, 0x13,
	0x1b, 0x22, 0xca, 0xf5, 0x5d, 0x7c, 0x9c, 0x58, 0x93, 0xe1, 0x34, 0x49, 0x2b, 0x4e, 0xd3, 0x47,
	0x1c, 0xa4, 0x59, 0x43, 0x76, 0xa4, 0x55, 0xd8, 0xd7, 0x1d, 0x6f, 0xef, 0xd0, 0x39, 0xf8, 0x54,
	0x96, 0x1b, 0x22, 0xeb, 0xd8, 0x4d, 0xac, 0xc9, 0x00, 0x7b, 0x54, 0x2e, 0x88, 0xac, 0xd1, 0x15,
	0x78, 0x5b, 0xda, 0x28, 0x22, 0x62, 0x2f, 0xb1, 0x26, 0xe1, 0xf4, 0xe2, 0xaf, 0x77, 0xbe, 0xd3,
	0x32, 0xdc, 0xcb, 0x47, 0xdf, 0x2d, 0xf0, 0x0c, 0x84, 0x86, 0x60, 0xb3, 0x5b, 0x3d, 0x6b, 0x80,
	0x6d, 0x76, 0x8b, 0xde, 0xc3, 0x80, 0x97, 0x52, 0x55, 0x6a, 0x2f, 0xf5, 0x9c, 0xc3, 0xe9, 0xcb,
	0x7f, 0xdc, 0x9a, 0xf6, 0xf0, 0x4a, 0x37, 0x61, 0x9f, 0x9b, 0xc3, 0x78, 0x0e, 0xa7, 0x07, 0x0c,
	0xf2, 0xc1, 0x99, 0xe5, 0x79, 0x74, 0x84, 0x4e, 0x60, 0x30, 0x9b, 0xcf, 0xb3, 0x65, 0x91, 0x2d,
	0x22, 0xab, 0xab, 0x3e, 0x7f, 0x5c, 0x7d, 0xca, 0xbf, 0x64, 0x8b, 0xc8, 0x46, 0xa7, 0x10, 0xcc,
	0x8a, 0x22, 0xfb, 0xa0, 0x49, 0x67, 0xfc, 0x02, 0xfc, 0xfe, 0x7b, 0x74, 0xed, 0xcb, 0xeb, 0x45,
	0x74, 0x84, 0x02, 0x70, 0x8b, 0xeb, 0x22, 0xcf, 0x22, 0x0b, 0x85, 0xe0, 0xcf, 0xe6, 0x25, 0x9e,
	0x15, 0x59, 0x64, 0x8f, 0xbf, 0x39, 0x70, 0x76, 0x68, 0x53, 0x72, 0xd6, 0x4a, 0x82, 0xae, 0xc0,
	0x6d, 0x68, 0x4b, 0x64, 0x6c, 0x25, 0xce, 0x24, 0x9c, 0x5e, 0x3e, 0x32, 0x90, 0x51, 0xa6, 0x4b,
	0x22, 0x72, 0xda, 0x12, 0x6c, 0xf4, 0xe8, 0x02, 0x42, 0xc5, 0x54, 0xd5, 0x94, 0xa6, 0xdd, 0xe4,
	0x0e, 0x1a, 0xca, 0x0f, 0x05, 0x5d, 0xf0, 0xb2, 0x4f, 0xde, 0x08, 0xba, 0xdc, 0xe5, 0x83, 0xdd,
	0x38, 0x7e, 0xb8, 0x1b, 0x09, 0xb8, 0x44, 0x08, 0x26, 0x74, 0xb8, 0xe1, 0x14, 0xb4, 0xbb, 0xac,
	0x43, 0xb0, 0x21, 0x46, 0x3f, 0x2c, 0xf0, 0x7b, 0x67, 0x28, 0x02, 0x47, 0xd2, 0x4d, 0x1f, 0x58,
	0x77, 0xec, 0x13, 0xb4, 0xef, 0x13, 0x8c, 0xc0, 0xe1, 0x74, 0xa3, 0xbd, 0x04, 0xb8, 0x3b, 0xa2,
	0x33, 0x70, 0x15, 0x55, 0x8d, 0x79, 0x3d, 0xc0, 0xa6, 0xe8, 0x36, 0x5d, 0xb2, 0xbd, 0xa8, 0x89,
	0x7e, 0x38, 0xc0, 0x7d, 0x85, 0x9e, 0xc1, 0x69, 0x55, 0x97, 0x72, 0xbf, 0xde, 0x51, 0x29, 0x29,
	0x6b, 0xf5, 0x72, 0xb9, 0xf8, 0xa4, 0xaa, 0x57, 0xf7, 0x18, 0x7a, 0x0e, 0x91, 0x19, 0xfc, 0x0f,
	0x9d, 0xaf, 0x75, 0xff, 0x69, 0xfc, 0xb7, 0x74, 0xed, 0xe9, 0x1f, 0xee, 0xf5, 0xaf, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xa8, 0x51, 0xd2, 0x8f, 0xa2, 0x03, 0x00, 0x00,
}
