// Code generated by protoc-gen-go.
// source: api/list_submissions.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ListSubmissionsRequest struct {
	PerPage           int32                          `protobuf:"varint,1,opt,name=per_page,json=perPage" json:"per_page,omitempty"`
	CurrentPage       int32                          `protobuf:"varint,2,opt,name=current_page,json=currentPage" json:"current_page,omitempty"`
	Filter            *ListSubmissionsRequest_Filter `protobuf:"bytes,3,opt,name=filter" json:"filter,omitempty"`
	NeedLanguagesList bool                           `protobuf:"varint,4,opt,name=need_languages_list,json=needLanguagesList" json:"need_languages_list,omitempty"`
	NeedOjsList       bool                           `protobuf:"varint,5,opt,name=need_ojs_list,json=needOjsList" json:"need_ojs_list,omitempty"`
}

func (m *ListSubmissionsRequest) Reset()                    { *m = ListSubmissionsRequest{} }
func (m *ListSubmissionsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListSubmissionsRequest) ProtoMessage()               {}
func (*ListSubmissionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *ListSubmissionsRequest) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *ListSubmissionsRequest) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *ListSubmissionsRequest) GetFilter() *ListSubmissionsRequest_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListSubmissionsRequest) GetNeedLanguagesList() bool {
	if m != nil {
		return m.NeedLanguagesList
	}
	return false
}

func (m *ListSubmissionsRequest) GetNeedOjsList() bool {
	if m != nil {
		return m.NeedOjsList
	}
	return false
}

type ListSubmissionsRequest_Filter struct {
	Username   string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Oj         string `protobuf:"bytes,2,opt,name=oj" json:"oj,omitempty"`
	Pid        string `protobuf:"bytes,3,opt,name=pid" json:"pid,omitempty"`
	StatusCode string `protobuf:"bytes,4,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	Language   string `protobuf:"bytes,5,opt,name=language" json:"language,omitempty"`
	Compiler   string `protobuf:"bytes,6,opt,name=compiler" json:"compiler,omitempty"`
}

func (m *ListSubmissionsRequest_Filter) Reset()         { *m = ListSubmissionsRequest_Filter{} }
func (m *ListSubmissionsRequest_Filter) String() string { return proto.CompactTextString(m) }
func (*ListSubmissionsRequest_Filter) ProtoMessage()    {}
func (*ListSubmissionsRequest_Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{0, 0}
}

func (m *ListSubmissionsRequest_Filter) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ListSubmissionsRequest_Filter) GetOj() string {
	if m != nil {
		return m.Oj
	}
	return ""
}

func (m *ListSubmissionsRequest_Filter) GetPid() string {
	if m != nil {
		return m.Pid
	}
	return ""
}

func (m *ListSubmissionsRequest_Filter) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *ListSubmissionsRequest_Filter) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *ListSubmissionsRequest_Filter) GetCompiler() string {
	if m != nil {
		return m.Compiler
	}
	return ""
}

type ListSubmissionsResponse struct {
	Lines         []*ListSubmissionsResponse_PerLine `protobuf:"bytes,1,rep,name=lines" json:"lines,omitempty"`
	TotalLines    int32                              `protobuf:"varint,2,opt,name=total_lines,json=totalLines" json:"total_lines,omitempty"`
	TotalPages    int32                              `protobuf:"varint,3,opt,name=total_pages,json=totalPages" json:"total_pages,omitempty"`
	CurrentPage   int32                              `protobuf:"varint,4,opt,name=current_page,json=currentPage" json:"current_page,omitempty"`
	LanguagesList []*Language                        `protobuf:"bytes,5,rep,name=languages_list,json=languagesList" json:"languages_list,omitempty"`
	OjsList       []string                           `protobuf:"bytes,6,rep,name=ojs_list,json=ojsList" json:"ojs_list,omitempty"`
	Error         *Error                             `protobuf:"bytes,7,opt,name=error" json:"error,omitempty"`
}

func (m *ListSubmissionsResponse) Reset()                    { *m = ListSubmissionsResponse{} }
func (m *ListSubmissionsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListSubmissionsResponse) ProtoMessage()               {}
func (*ListSubmissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *ListSubmissionsResponse) GetLines() []*ListSubmissionsResponse_PerLine {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *ListSubmissionsResponse) GetTotalLines() int32 {
	if m != nil {
		return m.TotalLines
	}
	return 0
}

func (m *ListSubmissionsResponse) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *ListSubmissionsResponse) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *ListSubmissionsResponse) GetLanguagesList() []*Language {
	if m != nil {
		return m.LanguagesList
	}
	return nil
}

func (m *ListSubmissionsResponse) GetOjsList() []string {
	if m != nil {
		return m.OjsList
	}
	return nil
}

func (m *ListSubmissionsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ListSubmissionsResponse_PerLine struct {
	Sid             string    `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
	RunId           int64     `protobuf:"varint,2,opt,name=run_id,json=runId" json:"run_id,omitempty"`
	Username        string    `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Status          string    `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	StatusCode      string    `protobuf:"bytes,5,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	CeInfo          string    `protobuf:"bytes,6,opt,name=ce_info,json=ceInfo" json:"ce_info,omitempty"`
	Language        *Language `protobuf:"bytes,7,opt,name=language" json:"language,omitempty"`
	TimeUsed        int32     `protobuf:"varint,8,opt,name=time_used,json=timeUsed" json:"time_used,omitempty"`
	MemoryUsed      int32     `protobuf:"varint,9,opt,name=memory_used,json=memoryUsed" json:"memory_used,omitempty"`
	Testcases       int32     `protobuf:"varint,10,opt,name=testcases" json:"testcases,omitempty"`
	TestcasesPassed int32     `protobuf:"varint,11,opt,name=testcases_passed,json=testcasesPassed" json:"testcases_passed,omitempty"`
	CodeLength      int32     `protobuf:"varint,12,opt,name=code_length,json=codeLength" json:"code_length,omitempty"`
	SubmitTime      string    `protobuf:"bytes,13,opt,name=submit_time,json=submitTime" json:"submit_time,omitempty"`
	Code            string    `protobuf:"bytes,14,opt,name=code" json:"code,omitempty"`
	IsSpj           bool      `protobuf:"varint,15,opt,name=is_spj,json=isSpj" json:"is_spj,omitempty"`
}

func (m *ListSubmissionsResponse_PerLine) Reset()         { *m = ListSubmissionsResponse_PerLine{} }
func (m *ListSubmissionsResponse_PerLine) String() string { return proto.CompactTextString(m) }
func (*ListSubmissionsResponse_PerLine) ProtoMessage()    {}
func (*ListSubmissionsResponse_PerLine) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{1, 0}
}

func (m *ListSubmissionsResponse_PerLine) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *ListSubmissionsResponse_PerLine) GetRunId() int64 {
	if m != nil {
		return m.RunId
	}
	return 0
}

func (m *ListSubmissionsResponse_PerLine) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ListSubmissionsResponse_PerLine) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ListSubmissionsResponse_PerLine) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *ListSubmissionsResponse_PerLine) GetCeInfo() string {
	if m != nil {
		return m.CeInfo
	}
	return ""
}

func (m *ListSubmissionsResponse_PerLine) GetLanguage() *Language {
	if m != nil {
		return m.Language
	}
	return nil
}

func (m *ListSubmissionsResponse_PerLine) GetTimeUsed() int32 {
	if m != nil {
		return m.TimeUsed
	}
	return 0
}

func (m *ListSubmissionsResponse_PerLine) GetMemoryUsed() int32 {
	if m != nil {
		return m.MemoryUsed
	}
	return 0
}

func (m *ListSubmissionsResponse_PerLine) GetTestcases() int32 {
	if m != nil {
		return m.Testcases
	}
	return 0
}

func (m *ListSubmissionsResponse_PerLine) GetTestcasesPassed() int32 {
	if m != nil {
		return m.TestcasesPassed
	}
	return 0
}

func (m *ListSubmissionsResponse_PerLine) GetCodeLength() int32 {
	if m != nil {
		return m.CodeLength
	}
	return 0
}

func (m *ListSubmissionsResponse_PerLine) GetSubmitTime() string {
	if m != nil {
		return m.SubmitTime
	}
	return ""
}

func (m *ListSubmissionsResponse_PerLine) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ListSubmissionsResponse_PerLine) GetIsSpj() bool {
	if m != nil {
		return m.IsSpj
	}
	return false
}

func init() {
	proto.RegisterType((*ListSubmissionsRequest)(nil), "api.ListSubmissionsRequest")
	proto.RegisterType((*ListSubmissionsRequest_Filter)(nil), "api.ListSubmissionsRequest.Filter")
	proto.RegisterType((*ListSubmissionsResponse)(nil), "api.ListSubmissionsResponse")
	proto.RegisterType((*ListSubmissionsResponse_PerLine)(nil), "api.ListSubmissionsResponse.PerLine")
}

func init() { proto.RegisterFile("api/list_submissions.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x54, 0xc1, 0x6e, 0xd3, 0x4c,
	0x10, 0x56, 0xea, 0xda, 0x89, 0x27, 0x4d, 0xdb, 0x7f, 0x7f, 0xd1, 0xba, 0x01, 0x89, 0x10, 0x71,
	0x48, 0x2f, 0x41, 0x2a, 0x9c, 0xb8, 0x22, 0x90, 0x2a, 0x45, 0xa2, 0xda, 0xc2, 0xd9, 0x72, 0xe3,
	0x69, 0xd8, 0xc8, 0xde, 0x35, 0x3b, 0xeb, 0x03, 0x6f, 0xc0, 0x5b, 0xf0, 0x28, 0x3c, 0x12, 0xaf,
	0x80, 0x76, 0xd6, 0x49, 0x69, 0xd2, 0xdb, 0xce, 0xf7, 0x7d, 0x3b, 0x3b, 0x33, 0xdf, 0xd8, 0x30,
	0x2e, 0x1a, 0xf5, 0xa6, 0x52, 0xe4, 0x72, 0x6a, 0xef, 0x6a, 0x45, 0xa4, 0x8c, 0xa6, 0x79, 0x63,
	0x8d, 0x33, 0x22, 0x2a, 0x1a, 0x35, 0x3e, 0xf5, 0x82, 0xa5, 0xa9, 0x6b, 0xa3, 0x03, 0x3c, 0x16,
	0x7c, 0xa5, 0xd0, 0xab, 0xb6, 0x58, 0x61, 0xc0, 0xa6, 0x3f, 0x23, 0x38, 0x5b, 0x28, 0x72, 0xb7,
	0x0f, 0x49, 0x24, 0x7e, 0x6f, 0x91, 0x9c, 0xb8, 0x80, 0x41, 0x83, 0x36, 0x6f, 0x8a, 0x15, 0x66,
	0xbd, 0x49, 0x6f, 0x16, 0xcb, 0x7e, 0x83, 0xf6, 0xa6, 0x58, 0xa1, 0x78, 0x05, 0x47, 0xcb, 0xd6,
	0x5a, 0xd4, 0x2e, 0xd0, 0x07, 0x4c, 0x0f, 0x3b, 0x8c, 0x25, 0xef, 0x21, 0xb9, 0x57, 0x95, 0x43,
	0x9b, 0x45, 0x93, 0xde, 0x6c, 0x78, 0x35, 0x9d, 0x17, 0x8d, 0x9a, 0x3f, 0xfd, 0xd4, 0xfc, 0x13,
	0x2b, 0x65, 0x77, 0x43, 0xcc, 0xe1, 0x7f, 0x8d, 0x58, 0xe6, 0x9b, 0x5a, 0x29, 0xf7, 0x8d, 0x66,
	0x87, 0x93, 0xde, 0x6c, 0x20, 0xff, 0xf3, 0xd4, 0x62, 0xc3, 0xf8, 0x84, 0x62, 0x0a, 0x23, 0xd6,
	0x9b, 0x75, 0xa7, 0x8c, 0x59, 0x39, 0xf4, 0xe0, 0xe7, 0x35, 0x6b, 0xc6, 0xbf, 0x7a, 0x90, 0x84,
	0x67, 0xc4, 0x18, 0x06, 0x2d, 0xa1, 0xd5, 0x45, 0x1d, 0x1a, 0x4b, 0xe5, 0x36, 0x16, 0xc7, 0x70,
	0x60, 0xd6, 0xdc, 0x4f, 0x2a, 0x0f, 0xcc, 0x5a, 0x9c, 0x42, 0xd4, 0xa8, 0x92, 0x7b, 0x48, 0xa5,
	0x3f, 0x8a, 0x97, 0x30, 0x24, 0x57, 0xb8, 0x96, 0xf2, 0xa5, 0x29, 0x91, 0x8b, 0x4a, 0x25, 0x04,
	0xe8, 0x83, 0x29, 0xd1, 0xa7, 0xdf, 0x14, 0xce, 0x85, 0xa4, 0x72, 0x1b, 0x7b, 0x6e, 0x69, 0xea,
	0x46, 0x55, 0x68, 0xb3, 0x24, 0x70, 0x9b, 0x78, 0xfa, 0x27, 0x86, 0xf3, 0xbd, 0xf9, 0x50, 0x63,
	0x34, 0xf9, 0x69, 0xc6, 0x95, 0xd2, 0x48, 0x59, 0x6f, 0x12, 0xcd, 0x86, 0x57, 0xaf, 0x9f, 0x1e,
	0x66, 0x10, 0xcf, 0x6f, 0xd0, 0x2e, 0x94, 0x46, 0x19, 0xae, 0xf8, 0x82, 0x9d, 0x71, 0x45, 0x95,
	0x87, 0x0c, 0xc1, 0x2b, 0x60, 0x68, 0xf1, 0x58, 0xe0, 0xbd, 0x24, 0xee, 0x75, 0x23, 0xf0, 0x56,
	0xd2, 0x9e, 0xdd, 0x87, 0xfb, 0x76, 0xbf, 0x83, 0xe3, 0x1d, 0xb7, 0x62, 0xae, 0x74, 0x14, 0x2a,
	0xed, 0x28, 0x39, 0xaa, 0x1e, 0x19, 0x77, 0x01, 0x83, 0xad, 0x67, 0xc9, 0x24, 0x9a, 0xa5, 0xb2,
	0x6f, 0x82, 0x5f, 0x62, 0x02, 0x31, 0x5a, 0x6b, 0x6c, 0xd6, 0xe7, 0xf5, 0x01, 0xce, 0xf3, 0xd1,
	0x23, 0x32, 0x10, 0xe3, 0xdf, 0x11, 0xf4, 0xbb, 0x56, 0xbd, 0x4d, 0xa4, 0xca, 0xce, 0x4d, 0x7f,
	0x14, 0xcf, 0x20, 0xb1, 0xad, 0xce, 0x55, 0xc9, 0x0d, 0x47, 0x32, 0xb6, 0xad, 0xbe, 0x2e, 0x1f,
	0x79, 0x1f, 0xed, 0x78, 0x7f, 0x06, 0x49, 0xb0, 0xb1, 0x33, 0xb5, 0x8b, 0x76, 0x1d, 0x8f, 0xf7,
	0x1c, 0x3f, 0x87, 0xfe, 0x12, 0x73, 0xa5, 0xef, 0x4d, 0x67, 0x6a, 0xb2, 0xc4, 0x6b, 0x7d, 0x6f,
	0xc4, 0xe5, 0x3f, 0xab, 0x10, 0xfa, 0xd8, 0x99, 0xc7, 0xc3, 0x66, 0x3c, 0x87, 0xd4, 0xa9, 0x1a,
	0xf3, 0x96, 0xb0, 0xcc, 0x06, 0x3c, 0xe0, 0x81, 0x07, 0xbe, 0x12, 0xf2, 0xce, 0xd5, 0x58, 0x1b,
	0xfb, 0x23, 0xd0, 0x69, 0x70, 0x28, 0x40, 0x2c, 0x78, 0x01, 0xa9, 0x43, 0x72, 0xcb, 0x82, 0x90,
	0x32, 0x60, 0xfa, 0x01, 0x10, 0x97, 0x70, 0xba, 0x0d, 0xf2, 0xa6, 0x20, 0x9f, 0x63, 0xc8, 0xa2,
	0x93, 0x2d, 0x7e, 0xc3, 0xb0, 0x7f, 0xc9, 0x37, 0x99, 0x57, 0xa8, 0x57, 0xee, 0x5b, 0x76, 0x14,
	0x5e, 0xf2, 0xd0, 0x82, 0x11, 0x1e, 0x86, 0xdf, 0x39, 0x97, 0xfb, 0xea, 0xb2, 0x51, 0x37, 0x0c,
	0x86, 0xbe, 0xa8, 0x1a, 0x85, 0x80, 0x43, 0x1e, 0xd3, 0x31, 0x33, 0x7c, 0xf6, 0x66, 0x28, 0xca,
	0xa9, 0x59, 0x67, 0x27, 0xfc, 0x65, 0xc6, 0x8a, 0x6e, 0x9b, 0xf5, 0x5d, 0xc2, 0xff, 0xa0, 0xb7,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x86, 0xff, 0x93, 0x6b, 0xcc, 0x04, 0x00, 0x00,
}
