// Code generated by protoc-gen-go.
// source: rpc/daemon.proto
// DO NOT EDIT!

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc/daemon.proto

It has these top-level messages:
	UpdateSubmissionStatusRequest
	UpdateSubmissionStatusResponse
	UpdateProblemDescriptionRequest
	UpdateProblemDescriptionResponse
	GetTestingDataRequest
	GetTestingDataResponse
	StartJudgingRequest
	StartJudgingResponse
	RegisterRequest
	RegisterResponse
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UpdateSubmissionStatusRequest struct {
	RunId           int64  `protobuf:"varint,1,opt,name=run_id,json=runId" json:"run_id,omitempty"`
	Status          string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
	StatusCode      string `protobuf:"bytes,3,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	TestcasesPassed int32  `protobuf:"varint,4,opt,name=testcases_passed,json=testcasesPassed" json:"testcases_passed,omitempty"`
	TimeUsed        int32  `protobuf:"varint,5,opt,name=time_used,json=timeUsed" json:"time_used,omitempty"`
	MemoryUsed      int32  `protobuf:"varint,6,opt,name=memory_used,json=memoryUsed" json:"memory_used,omitempty"`
	CeInfo          string `protobuf:"bytes,7,opt,name=ce_info,json=ceInfo" json:"ce_info,omitempty"`
}

func (m *UpdateSubmissionStatusRequest) Reset()                    { *m = UpdateSubmissionStatusRequest{} }
func (m *UpdateSubmissionStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateSubmissionStatusRequest) ProtoMessage()               {}
func (*UpdateSubmissionStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UpdateSubmissionStatusRequest) GetRunId() int64 {
	if m != nil {
		return m.RunId
	}
	return 0
}

func (m *UpdateSubmissionStatusRequest) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *UpdateSubmissionStatusRequest) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *UpdateSubmissionStatusRequest) GetTestcasesPassed() int32 {
	if m != nil {
		return m.TestcasesPassed
	}
	return 0
}

func (m *UpdateSubmissionStatusRequest) GetTimeUsed() int32 {
	if m != nil {
		return m.TimeUsed
	}
	return 0
}

func (m *UpdateSubmissionStatusRequest) GetMemoryUsed() int32 {
	if m != nil {
		return m.MemoryUsed
	}
	return 0
}

func (m *UpdateSubmissionStatusRequest) GetCeInfo() string {
	if m != nil {
		return m.CeInfo
	}
	return ""
}

type UpdateSubmissionStatusResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *UpdateSubmissionStatusResponse) Reset()                    { *m = UpdateSubmissionStatusResponse{} }
func (m *UpdateSubmissionStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateSubmissionStatusResponse) ProtoMessage()               {}
func (*UpdateSubmissionStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateSubmissionStatusResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type UpdateProblemDescriptionRequest struct {
}

func (m *UpdateProblemDescriptionRequest) Reset()                    { *m = UpdateProblemDescriptionRequest{} }
func (m *UpdateProblemDescriptionRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateProblemDescriptionRequest) ProtoMessage()               {}
func (*UpdateProblemDescriptionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type UpdateProblemDescriptionResponse struct {
}

func (m *UpdateProblemDescriptionResponse) Reset()         { *m = UpdateProblemDescriptionResponse{} }
func (m *UpdateProblemDescriptionResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateProblemDescriptionResponse) ProtoMessage()    {}
func (*UpdateProblemDescriptionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3}
}

type GetTestingDataRequest struct {
	OnlyHash bool  `protobuf:"varint,1,opt,name=only_hash,json=onlyHash" json:"only_hash,omitempty"`
	LocalPid int64 `protobuf:"varint,2,opt,name=local_pid,json=localPid" json:"local_pid,omitempty"`
}

func (m *GetTestingDataRequest) Reset()                    { *m = GetTestingDataRequest{} }
func (m *GetTestingDataRequest) String() string            { return proto.CompactTextString(m) }
func (*GetTestingDataRequest) ProtoMessage()               {}
func (*GetTestingDataRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetTestingDataRequest) GetOnlyHash() bool {
	if m != nil {
		return m.OnlyHash
	}
	return false
}

func (m *GetTestingDataRequest) GetLocalPid() int64 {
	if m != nil {
		return m.LocalPid
	}
	return 0
}

type GetTestingDataResponse struct {
	Spj   *GetTestingDataResponse_Spj    `protobuf:"bytes,1,opt,name=spj" json:"spj,omitempty"`
	Cases []*GetTestingDataResponse_Case `protobuf:"bytes,2,rep,name=cases" json:"cases,omitempty"`
}

func (m *GetTestingDataResponse) Reset()                    { *m = GetTestingDataResponse{} }
func (m *GetTestingDataResponse) String() string            { return proto.CompactTextString(m) }
func (*GetTestingDataResponse) ProtoMessage()               {}
func (*GetTestingDataResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetTestingDataResponse) GetSpj() *GetTestingDataResponse_Spj {
	if m != nil {
		return m.Spj
	}
	return nil
}

func (m *GetTestingDataResponse) GetCases() []*GetTestingDataResponse_Case {
	if m != nil {
		return m.Cases
	}
	return nil
}

type GetTestingDataResponse_Case struct {
	OnlyHash bool   `protobuf:"varint,1,opt,name=only_hash,json=onlyHash" json:"only_hash,omitempty"`
	InHash   string `protobuf:"bytes,2,opt,name=in_hash,json=inHash" json:"in_hash,omitempty"`
	In       string `protobuf:"bytes,3,opt,name=in" json:"in,omitempty"`
	OutHash  string `protobuf:"bytes,4,opt,name=out_hash,json=outHash" json:"out_hash,omitempty"`
	Out      string `protobuf:"bytes,5,opt,name=out" json:"out,omitempty"`
}

func (m *GetTestingDataResponse_Case) Reset()                    { *m = GetTestingDataResponse_Case{} }
func (m *GetTestingDataResponse_Case) String() string            { return proto.CompactTextString(m) }
func (*GetTestingDataResponse_Case) ProtoMessage()               {}
func (*GetTestingDataResponse_Case) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 0} }

func (m *GetTestingDataResponse_Case) GetOnlyHash() bool {
	if m != nil {
		return m.OnlyHash
	}
	return false
}

func (m *GetTestingDataResponse_Case) GetInHash() string {
	if m != nil {
		return m.InHash
	}
	return ""
}

func (m *GetTestingDataResponse_Case) GetIn() string {
	if m != nil {
		return m.In
	}
	return ""
}

func (m *GetTestingDataResponse_Case) GetOutHash() string {
	if m != nil {
		return m.OutHash
	}
	return ""
}

func (m *GetTestingDataResponse_Case) GetOut() string {
	if m != nil {
		return m.Out
	}
	return ""
}

type GetTestingDataResponse_Spj struct {
	OnlyHash    bool   `protobuf:"varint,1,opt,name=only_hash,json=onlyHash" json:"only_hash,omitempty"`
	SpjCodeHash string `protobuf:"bytes,2,opt,name=spj_code_hash,json=spjCodeHash" json:"spj_code_hash,omitempty"`
	SpjCode     string `protobuf:"bytes,3,opt,name=spj_code,json=spjCode" json:"spj_code,omitempty"`
}

func (m *GetTestingDataResponse_Spj) Reset()                    { *m = GetTestingDataResponse_Spj{} }
func (m *GetTestingDataResponse_Spj) String() string            { return proto.CompactTextString(m) }
func (*GetTestingDataResponse_Spj) ProtoMessage()               {}
func (*GetTestingDataResponse_Spj) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5, 1} }

func (m *GetTestingDataResponse_Spj) GetOnlyHash() bool {
	if m != nil {
		return m.OnlyHash
	}
	return false
}

func (m *GetTestingDataResponse_Spj) GetSpjCodeHash() string {
	if m != nil {
		return m.SpjCodeHash
	}
	return ""
}

func (m *GetTestingDataResponse_Spj) GetSpjCode() string {
	if m != nil {
		return m.SpjCode
	}
	return ""
}

type StartJudgingRequest struct {
	RunId int64 `protobuf:"varint,1,opt,name=run_id,json=runId" json:"run_id,omitempty"`
}

func (m *StartJudgingRequest) Reset()                    { *m = StartJudgingRequest{} }
func (m *StartJudgingRequest) String() string            { return proto.CompactTextString(m) }
func (*StartJudgingRequest) ProtoMessage()               {}
func (*StartJudgingRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StartJudgingRequest) GetRunId() int64 {
	if m != nil {
		return m.RunId
	}
	return 0
}

type StartJudgingResponse struct {
	Received bool `protobuf:"varint,1,opt,name=received" json:"received,omitempty"`
}

func (m *StartJudgingResponse) Reset()                    { *m = StartJudgingResponse{} }
func (m *StartJudgingResponse) String() string            { return proto.CompactTextString(m) }
func (*StartJudgingResponse) ProtoMessage()               {}
func (*StartJudgingResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *StartJudgingResponse) GetReceived() bool {
	if m != nil {
		return m.Received
	}
	return false
}

type RegisterRequest struct {
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type RegisterResponse struct {
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*UpdateSubmissionStatusRequest)(nil), "rpc.UpdateSubmissionStatusRequest")
	proto.RegisterType((*UpdateSubmissionStatusResponse)(nil), "rpc.UpdateSubmissionStatusResponse")
	proto.RegisterType((*UpdateProblemDescriptionRequest)(nil), "rpc.UpdateProblemDescriptionRequest")
	proto.RegisterType((*UpdateProblemDescriptionResponse)(nil), "rpc.UpdateProblemDescriptionResponse")
	proto.RegisterType((*GetTestingDataRequest)(nil), "rpc.GetTestingDataRequest")
	proto.RegisterType((*GetTestingDataResponse)(nil), "rpc.GetTestingDataResponse")
	proto.RegisterType((*GetTestingDataResponse_Case)(nil), "rpc.GetTestingDataResponse.Case")
	proto.RegisterType((*GetTestingDataResponse_Spj)(nil), "rpc.GetTestingDataResponse.Spj")
	proto.RegisterType((*StartJudgingRequest)(nil), "rpc.StartJudgingRequest")
	proto.RegisterType((*StartJudgingResponse)(nil), "rpc.StartJudgingResponse")
	proto.RegisterType((*RegisterRequest)(nil), "rpc.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "rpc.RegisterResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Helper service

type HelperClient interface {
	StartJudging(ctx context.Context, in *StartJudgingRequest, opts ...grpc.CallOption) (*StartJudgingResponse, error)
	GetTestingData(ctx context.Context, in *GetTestingDataRequest, opts ...grpc.CallOption) (*GetTestingDataResponse, error)
	// rpc GetDBInfo() returns (DBInfo) {}
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	UpdateProblemDescription(ctx context.Context, in *UpdateProblemDescriptionRequest, opts ...grpc.CallOption) (*UpdateProblemDescriptionResponse, error)
	UpdateSubmissionStatus(ctx context.Context, in *UpdateSubmissionStatusRequest, opts ...grpc.CallOption) (*UpdateSubmissionStatusResponse, error)
}

type helperClient struct {
	cc *grpc.ClientConn
}

func NewHelperClient(cc *grpc.ClientConn) HelperClient {
	return &helperClient{cc}
}

func (c *helperClient) StartJudging(ctx context.Context, in *StartJudgingRequest, opts ...grpc.CallOption) (*StartJudgingResponse, error) {
	out := new(StartJudgingResponse)
	err := grpc.Invoke(ctx, "/rpc.Helper/StartJudging", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helperClient) GetTestingData(ctx context.Context, in *GetTestingDataRequest, opts ...grpc.CallOption) (*GetTestingDataResponse, error) {
	out := new(GetTestingDataResponse)
	err := grpc.Invoke(ctx, "/rpc.Helper/GetTestingData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helperClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	out := new(RegisterResponse)
	err := grpc.Invoke(ctx, "/rpc.Helper/Register", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helperClient) UpdateProblemDescription(ctx context.Context, in *UpdateProblemDescriptionRequest, opts ...grpc.CallOption) (*UpdateProblemDescriptionResponse, error) {
	out := new(UpdateProblemDescriptionResponse)
	err := grpc.Invoke(ctx, "/rpc.Helper/UpdateProblemDescription", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helperClient) UpdateSubmissionStatus(ctx context.Context, in *UpdateSubmissionStatusRequest, opts ...grpc.CallOption) (*UpdateSubmissionStatusResponse, error) {
	out := new(UpdateSubmissionStatusResponse)
	err := grpc.Invoke(ctx, "/rpc.Helper/UpdateSubmissionStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Helper service

type HelperServer interface {
	StartJudging(context.Context, *StartJudgingRequest) (*StartJudgingResponse, error)
	GetTestingData(context.Context, *GetTestingDataRequest) (*GetTestingDataResponse, error)
	// rpc GetDBInfo() returns (DBInfo) {}
	Register(context.Context, *RegisterRequest) (*RegisterResponse, error)
	UpdateProblemDescription(context.Context, *UpdateProblemDescriptionRequest) (*UpdateProblemDescriptionResponse, error)
	UpdateSubmissionStatus(context.Context, *UpdateSubmissionStatusRequest) (*UpdateSubmissionStatusResponse, error)
}

func RegisterHelperServer(s *grpc.Server, srv HelperServer) {
	s.RegisterService(&_Helper_serviceDesc, srv)
}

func _Helper_StartJudging_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartJudgingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelperServer).StartJudging(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Helper/StartJudging",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelperServer).StartJudging(ctx, req.(*StartJudgingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helper_GetTestingData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTestingDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelperServer).GetTestingData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Helper/GetTestingData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelperServer).GetTestingData(ctx, req.(*GetTestingDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helper_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelperServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Helper/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelperServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helper_UpdateProblemDescription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProblemDescriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelperServer).UpdateProblemDescription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Helper/UpdateProblemDescription",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelperServer).UpdateProblemDescription(ctx, req.(*UpdateProblemDescriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Helper_UpdateSubmissionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubmissionStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelperServer).UpdateSubmissionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Helper/UpdateSubmissionStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelperServer).UpdateSubmissionStatus(ctx, req.(*UpdateSubmissionStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Helper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Helper",
	HandlerType: (*HelperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartJudging",
			Handler:    _Helper_StartJudging_Handler,
		},
		{
			MethodName: "GetTestingData",
			Handler:    _Helper_GetTestingData_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _Helper_Register_Handler,
		},
		{
			MethodName: "UpdateProblemDescription",
			Handler:    _Helper_UpdateProblemDescription_Handler,
		},
		{
			MethodName: "UpdateSubmissionStatus",
			Handler:    _Helper_UpdateSubmissionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/daemon.proto",
}

func init() { proto.RegisterFile("rpc/daemon.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 619 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x54, 0x5d, 0x6e, 0x13, 0x3d,
	0x14, 0x6d, 0x32, 0x4d, 0x32, 0xb9, 0xf9, 0xbe, 0x36, 0x98, 0xfe, 0x4c, 0xa7, 0x82, 0x04, 0x03,
	0x52, 0x90, 0x50, 0x10, 0x41, 0x42, 0x82, 0xd7, 0x16, 0xd1, 0xc2, 0x4b, 0x99, 0xd0, 0xe7, 0xc8,
	0xf5, 0xdc, 0xa6, 0x8e, 0x12, 0xdb, 0xd8, 0x1e, 0xa4, 0xae, 0x88, 0x75, 0xb1, 0x04, 0x76, 0x80,
	0xc6, 0x33, 0x53, 0xda, 0x2a, 0x49, 0xdf, 0xec, 0x73, 0x8e, 0xef, 0x8f, 0xef, 0xb1, 0xa1, 0x6b,
	0x34, 0x7f, 0x93, 0x32, 0x5c, 0x28, 0x39, 0xd4, 0x46, 0x39, 0x45, 0x02, 0xa3, 0x39, 0xfd, 0x53,
	0x83, 0x27, 0xe7, 0x3a, 0x65, 0x0e, 0xc7, 0xd9, 0xc5, 0x42, 0x58, 0x2b, 0x94, 0x1c, 0x3b, 0xe6,
	0x32, 0x9b, 0xe0, 0x8f, 0x0c, 0xad, 0x23, 0xbb, 0xd0, 0x34, 0x99, 0x9c, 0x88, 0x34, 0xaa, 0xf5,
	0x6b, 0x83, 0x20, 0x69, 0x98, 0x4c, 0x9e, 0xa6, 0x64, 0x0f, 0x9a, 0xd6, 0xeb, 0xa2, 0x7a, 0xbf,
	0x36, 0x68, 0x27, 0xe5, 0x8e, 0xf4, 0xa0, 0x53, 0xac, 0x26, 0x5c, 0xa5, 0x18, 0x05, 0x9e, 0x84,
	0x02, 0x3a, 0x52, 0x29, 0x92, 0x57, 0xd0, 0x75, 0x68, 0x1d, 0x67, 0x16, 0xed, 0x44, 0x33, 0x6b,
	0x31, 0x8d, 0x36, 0xfb, 0xb5, 0x41, 0x23, 0xd9, 0xbe, 0xc1, 0xcf, 0x3c, 0x4c, 0x0e, 0xa1, 0xed,
	0xc4, 0x02, 0x27, 0x59, 0xae, 0x69, 0x78, 0x4d, 0x98, 0x03, 0xe7, 0x39, 0xd9, 0x83, 0xce, 0x02,
	0x17, 0xca, 0x5c, 0x17, 0x74, 0xd3, 0xd3, 0x50, 0x40, 0x5e, 0xb0, 0x0f, 0x2d, 0x8e, 0x13, 0x21,
	0x2f, 0x55, 0xd4, 0x2a, 0x4a, 0xe4, 0x78, 0x2a, 0x2f, 0x15, 0xfd, 0x08, 0x4f, 0x57, 0xb5, 0x6c,
	0xb5, 0x92, 0x16, 0x49, 0x04, 0x2d, 0x9b, 0x71, 0x8e, 0xd6, 0xfa, 0xa6, 0xc3, 0xa4, 0xda, 0xd2,
	0x67, 0xd0, 0x2b, 0xce, 0x9e, 0x19, 0x75, 0x31, 0xc7, 0xc5, 0x31, 0x5a, 0x6e, 0x84, 0x76, 0x42,
	0xc9, 0xf2, 0xc2, 0x28, 0x85, 0xfe, 0x6a, 0x49, 0x91, 0x80, 0x7e, 0x83, 0xdd, 0xcf, 0xe8, 0xbe,
	0xa3, 0x75, 0x42, 0x4e, 0x8f, 0x99, 0x63, 0xd5, 0x6d, 0x1f, 0x42, 0x5b, 0xc9, 0xf9, 0xf5, 0xe4,
	0x8a, 0xd9, 0xab, 0x32, 0x77, 0x98, 0x03, 0x27, 0xcc, 0x5e, 0xe5, 0xe4, 0x5c, 0x71, 0x36, 0x9f,
	0x68, 0x91, 0xfa, 0x6b, 0x0f, 0x92, 0xd0, 0x03, 0x67, 0x22, 0xa5, 0xbf, 0xeb, 0xb0, 0x77, 0x3f,
	0x66, 0xd9, 0xce, 0x5b, 0x08, 0xac, 0x9e, 0xf9, 0x70, 0x9d, 0x51, 0x6f, 0x68, 0x34, 0x1f, 0x2e,
	0x57, 0x0e, 0xc7, 0x7a, 0x96, 0xe4, 0x5a, 0xf2, 0x1e, 0x1a, 0x7e, 0x12, 0x51, 0xbd, 0x1f, 0x0c,
	0x3a, 0xa3, 0xfe, 0xba, 0x43, 0x47, 0xcc, 0x62, 0x52, 0xc8, 0xe3, 0x6b, 0xd8, 0xcc, 0xb7, 0xeb,
	0xfb, 0xd8, 0x87, 0x96, 0x90, 0x05, 0x55, 0x9a, 0x47, 0x48, 0x4f, 0x6c, 0x41, 0x5d, 0xc8, 0xd2,
	0x33, 0x75, 0x21, 0xc9, 0x01, 0x84, 0x2a, 0x73, 0x85, 0x72, 0xd3, 0xa3, 0x2d, 0x95, 0x39, 0x2f,
	0xed, 0x42, 0xa0, 0x32, 0xe7, 0x5d, 0xd1, 0x4e, 0xf2, 0x65, 0xcc, 0x20, 0x18, 0xeb, 0xd9, 0xfa,
	0xcc, 0x14, 0xfe, 0xb7, 0x7a, 0xe6, 0xad, 0x79, 0x3b, 0x7f, 0xc7, 0xea, 0x59, 0x6e, 0x4e, 0xaf,
	0x39, 0x80, 0xb0, 0xd2, 0x94, 0xa5, 0xb4, 0x4a, 0x9a, 0xbe, 0x86, 0xc7, 0x63, 0xc7, 0x8c, 0xfb,
	0x92, 0xa5, 0x53, 0x21, 0xa7, 0xeb, 0x9f, 0x08, 0x1d, 0xc1, 0xce, 0x5d, 0x75, 0x39, 0x8e, 0x18,
	0x42, 0x83, 0x1c, 0xc5, 0x4f, 0x4c, 0xab, 0x02, 0xab, 0x3d, 0x7d, 0x04, 0xdb, 0x09, 0x4e, 0x85,
	0x75, 0x68, 0x2a, 0x3f, 0x11, 0xe8, 0xfe, 0x83, 0x8a, 0x10, 0xa3, 0x5f, 0x01, 0x34, 0x4f, 0x70,
	0xae, 0xd1, 0x90, 0x4f, 0xf0, 0xdf, 0xed, 0x2c, 0x24, 0xf2, 0xa3, 0x5a, 0x52, 0x66, 0x7c, 0xb0,
	0x84, 0x29, 0xfd, 0xb8, 0x41, 0xbe, 0xc2, 0xd6, 0xdd, 0xf1, 0x92, 0x78, 0xe9, 0xcc, 0x8b, 0x50,
	0x87, 0x6b, 0xfc, 0x40, 0x37, 0xc8, 0x07, 0x08, 0xab, 0x92, 0xc9, 0x8e, 0x97, 0xde, 0x6b, 0x2a,
	0xde, 0xbd, 0x87, 0xde, 0x1c, 0x15, 0x10, 0xad, 0x7a, 0x3d, 0xe4, 0x85, 0x3f, 0xf4, 0xc0, 0xfb,
	0x8b, 0x5f, 0x3e, 0xa0, 0xba, 0x49, 0xc5, 0x61, 0x6f, 0xf9, 0x3f, 0x40, 0xe8, 0xad, 0x10, 0x2b,
	0xfe, 0xc5, 0xf8, 0xf9, 0x5a, 0x4d, 0x95, 0xe4, 0xa2, 0xe9, 0x3f, 0xdb, 0x77, 0x7f, 0x03, 0x00,
	0x00, 0xff, 0xff, 0xf6, 0x9e, 0x70, 0x6c, 0x80, 0x05, 0x00, 0x00,
}
