// Code generated by protoc-gen-go.
// source: backend.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	backend.proto

It has these top-level messages:
	SubmitRequest
	SubmitResponse
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SubmitRequest struct {
	RunId int64 `protobuf:"varint,1,opt,name=run_id,json=runId" json:"run_id,omitempty"`
}

func (m *SubmitRequest) Reset()                    { *m = SubmitRequest{} }
func (m *SubmitRequest) String() string            { return proto.CompactTextString(m) }
func (*SubmitRequest) ProtoMessage()               {}
func (*SubmitRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SubmitRequest) GetRunId() int64 {
	if m != nil {
		return m.RunId
	}
	return 0
}

type SubmitResponse struct {
	Received bool `protobuf:"varint,1,opt,name=received" json:"received,omitempty"`
}

func (m *SubmitResponse) Reset()                    { *m = SubmitResponse{} }
func (m *SubmitResponse) String() string            { return proto.CompactTextString(m) }
func (*SubmitResponse) ProtoMessage()               {}
func (*SubmitResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SubmitResponse) GetReceived() bool {
	if m != nil {
		return m.Received
	}
	return false
}

func init() {
	proto.RegisterType((*SubmitRequest)(nil), "pb.SubmitRequest")
	proto.RegisterType((*SubmitResponse)(nil), "pb.SubmitResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BackendHelper service

type BackendHelperClient interface {
	Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error)
}

type backendHelperClient struct {
	cc *grpc.ClientConn
}

func NewBackendHelperClient(cc *grpc.ClientConn) BackendHelperClient {
	return &backendHelperClient{cc}
}

func (c *backendHelperClient) Submit(ctx context.Context, in *SubmitRequest, opts ...grpc.CallOption) (*SubmitResponse, error) {
	out := new(SubmitResponse)
	err := grpc.Invoke(ctx, "/pb.BackendHelper/Submit", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BackendHelper service

type BackendHelperServer interface {
	Submit(context.Context, *SubmitRequest) (*SubmitResponse, error)
}

func RegisterBackendHelperServer(s *grpc.Server, srv BackendHelperServer) {
	s.RegisterService(&_BackendHelper_serviceDesc, srv)
}

func _BackendHelper_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BackendHelperServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.BackendHelper/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BackendHelperServer).Submit(ctx, req.(*SubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BackendHelper_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.BackendHelper",
	HandlerType: (*BackendHelperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _BackendHelper_Submit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend.proto",
}

func init() { proto.RegisterFile("backend.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 153 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4a, 0x4c, 0xce,
	0x4e, 0xcd, 0x4b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x52, 0xe3,
	0xe2, 0x0d, 0x2e, 0x4d, 0xca, 0xcd, 0x2c, 0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12,
	0xe5, 0x62, 0x2b, 0x2a, 0xcd, 0x8b, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0e, 0x62,
	0x2d, 0x2a, 0xcd, 0xf3, 0x4c, 0x51, 0xd2, 0xe1, 0xe2, 0x83, 0xa9, 0x2b, 0x2e, 0xc8, 0xcf, 0x2b,
	0x4e, 0x15, 0x92, 0xe2, 0xe2, 0x28, 0x4a, 0x4d, 0x4e, 0xcd, 0x2c, 0x4b, 0x85, 0x28, 0xe5, 0x08,
	0x82, 0xf3, 0x8d, 0x9c, 0xb8, 0x78, 0x9d, 0x20, 0x56, 0x79, 0xa4, 0xe6, 0x14, 0xa4, 0x16, 0x09,
	0x19, 0x72, 0xb1, 0x41, 0xb4, 0x0b, 0x09, 0xea, 0x15, 0x24, 0xe9, 0xa1, 0x58, 0x29, 0x25, 0x84,
	0x2c, 0x04, 0x31, 0x5d, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x48, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0xdf, 0x77, 0xe2, 0x8a, 0xb5, 0x00, 0x00, 0x00,
}
