// Code generated by protoc-gen-go.
// source: messages/mq.proto
// DO NOT EDIT!

/*
Package messages is a generated protocol buffer package.

It is generated from these files:
	messages/mq.proto

It has these top-level messages:
	TestCase
	SpjCode
	SubmitMQ
*/
package messages

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TestCase struct {
	CaseId     int64  `protobuf:"varint,1,opt,name=case_id,json=caseId" json:"case_id,omitempty"`
	InputHash  []byte `protobuf:"bytes,2,opt,name=input_hash,json=inputHash,proto3" json:"input_hash,omitempty"`
	OutputHash []byte `protobuf:"bytes,3,opt,name=output_hash,json=outputHash,proto3" json:"output_hash,omitempty"`
	Input      string `protobuf:"bytes,4,opt,name=input" json:"input,omitempty"`
	Output     string `protobuf:"bytes,5,opt,name=output" json:"output,omitempty"`
}

func (m *TestCase) Reset()                    { *m = TestCase{} }
func (m *TestCase) String() string            { return proto.CompactTextString(m) }
func (*TestCase) ProtoMessage()               {}
func (*TestCase) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TestCase) GetCaseId() int64 {
	if m != nil {
		return m.CaseId
	}
	return 0
}

func (m *TestCase) GetInputHash() []byte {
	if m != nil {
		return m.InputHash
	}
	return nil
}

func (m *TestCase) GetOutputHash() []byte {
	if m != nil {
		return m.OutputHash
	}
	return nil
}

func (m *TestCase) GetInput() string {
	if m != nil {
		return m.Input
	}
	return ""
}

func (m *TestCase) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

type SpjCode struct {
	LocalPid int64  `protobuf:"varint,1,opt,name=local_pid,json=localPid" json:"local_pid,omitempty"`
	Hash     []byte `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	Code     string `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
}

func (m *SpjCode) Reset()                    { *m = SpjCode{} }
func (m *SpjCode) String() string            { return proto.CompactTextString(m) }
func (*SpjCode) ProtoMessage()               {}
func (*SpjCode) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SpjCode) GetLocalPid() int64 {
	if m != nil {
		return m.LocalPid
	}
	return 0
}

func (m *SpjCode) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *SpjCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SubmitMQ struct {
	RunId     int64       `protobuf:"varint,1,opt,name=run_id,json=runId" json:"run_id,omitempty"`
	OjName    string      `protobuf:"bytes,2,opt,name=oj_name,json=ojName" json:"oj_name,omitempty"`
	OjPid     int64       `protobuf:"varint,3,opt,name=oj_pid,json=ojPid" json:"oj_pid,omitempty"`
	Code      string      `protobuf:"bytes,4,opt,name=code" json:"code,omitempty"`
	IsLocal   bool        `protobuf:"varint,5,opt,name=is_local,json=isLocal" json:"is_local,omitempty"`
	IsSpj     bool        `protobuf:"varint,6,opt,name=is_spj,json=isSpj" json:"is_spj,omitempty"`
	Testcases []*TestCase `protobuf:"bytes,7,rep,name=testcases" json:"testcases,omitempty"`
}

func (m *SubmitMQ) Reset()                    { *m = SubmitMQ{} }
func (m *SubmitMQ) String() string            { return proto.CompactTextString(m) }
func (*SubmitMQ) ProtoMessage()               {}
func (*SubmitMQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SubmitMQ) GetRunId() int64 {
	if m != nil {
		return m.RunId
	}
	return 0
}

func (m *SubmitMQ) GetOjName() string {
	if m != nil {
		return m.OjName
	}
	return ""
}

func (m *SubmitMQ) GetOjPid() int64 {
	if m != nil {
		return m.OjPid
	}
	return 0
}

func (m *SubmitMQ) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *SubmitMQ) GetIsLocal() bool {
	if m != nil {
		return m.IsLocal
	}
	return false
}

func (m *SubmitMQ) GetIsSpj() bool {
	if m != nil {
		return m.IsSpj
	}
	return false
}

func (m *SubmitMQ) GetTestcases() []*TestCase {
	if m != nil {
		return m.Testcases
	}
	return nil
}

func init() {
	proto.RegisterType((*TestCase)(nil), "messages.TestCase")
	proto.RegisterType((*SpjCode)(nil), "messages.SpjCode")
	proto.RegisterType((*SubmitMQ)(nil), "messages.SubmitMQ")
}

func init() { proto.RegisterFile("messages/mq.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x51, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0x54, 0xbe, 0x34, 0x7f, 0xdb, 0xef, 0xc2, 0x8a, 0x9f, 0x20, 0x84, 0x88, 0x7a, 0xca, 0xa9,
	0x20, 0x78, 0x84, 0x5e, 0xa8, 0x04, 0x15, 0xa4, 0xdc, 0x23, 0xb7, 0xb1, 0xa8, 0xad, 0x26, 0x36,
	0x5d, 0xe7, 0x41, 0x78, 0x2c, 0xde, 0x0a, 0x79, 0xd3, 0x1f, 0x6e, 0x9e, 0xd9, 0xd1, 0xce, 0xac,
	0x07, 0xce, 0x5a, 0x49, 0x24, 0x3e, 0x25, 0xdd, 0xb7, 0x5f, 0x53, 0xbb, 0x33, 0xce, 0x60, 0x7a,
	0xa0, 0x26, 0xdf, 0x01, 0xa4, 0x1f, 0x92, 0xdc, 0x4c, 0x90, 0xc4, 0x2b, 0x48, 0xd6, 0x82, 0x64,
	0xad, 0x9a, 0x3c, 0x28, 0x82, 0x32, 0xac, 0x62, 0x0f, 0xe7, 0x0d, 0xde, 0x02, 0xa8, 0xce, 0xf6,
	0xae, 0xde, 0x08, 0xda, 0xe4, 0xff, 0x8a, 0xa0, 0xfc, 0x5f, 0x65, 0xcc, 0x3c, 0x0b, 0xda, 0xe0,
	0x1d, 0x8c, 0x4d, 0xef, 0x8e, 0xf3, 0x90, 0xe7, 0x30, 0x50, 0x2c, 0x38, 0x87, 0x88, 0xd5, 0xf9,
	0xa8, 0x08, 0xca, 0xac, 0x1a, 0x00, 0x5e, 0x42, 0x3c, 0x68, 0xf2, 0x88, 0xe9, 0x3d, 0x9a, 0x2c,
	0x20, 0x59, 0x5a, 0x3d, 0x33, 0x8d, 0xc4, 0x1b, 0xc8, 0xb6, 0x66, 0x2d, 0xb6, 0xb5, 0x3d, 0x66,
	0x4a, 0x99, 0x78, 0x53, 0x0d, 0x22, 0x8c, 0xfe, 0xe4, 0xe1, 0xb7, 0xe7, 0xd6, 0xa6, 0x91, 0x9c,
	0x21, 0xab, 0xf8, 0x3d, 0xf9, 0x09, 0x20, 0x5d, 0xf6, 0xab, 0x56, 0xb9, 0xd7, 0x77, 0xbc, 0x80,
	0x78, 0xd7, 0x77, 0xa7, 0x13, 0xa3, 0x5d, 0xdf, 0xcd, 0x1b, 0x7f, 0xba, 0xd1, 0x75, 0x27, 0x5a,
	0xc9, 0xeb, 0x7c, 0x18, 0xbd, 0x10, 0xad, 0xf4, 0x7a, 0xa3, 0xd9, 0x3e, 0x1c, 0xf4, 0x46, 0xef,
	0xbd, 0xd9, 0x67, 0x74, 0xf2, 0xc1, 0x6b, 0x48, 0x15, 0xd5, 0x1c, 0x8f, 0x2f, 0x4a, 0xab, 0x44,
	0xd1, 0x8b, 0x87, 0x7e, 0x8b, 0xa2, 0x9a, 0xac, 0xce, 0x63, 0x1e, 0x44, 0x8a, 0x96, 0x56, 0xe3,
	0x03, 0x64, 0x4e, 0x92, 0xf3, 0xbf, 0x4c, 0x79, 0x52, 0x84, 0xe5, 0xf8, 0x11, 0xa7, 0x87, 0x6e,
	0xa6, 0x87, 0x5e, 0xaa, 0x93, 0x68, 0x15, 0x73, 0x81, 0x4f, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xd9, 0x1d, 0xfb, 0x2a, 0xd5, 0x01, 0x00, 0x00,
}
