// Code generated by protoc-gen-go.
// source: api/about.proto
// DO NOT EDIT!

/*
Package api is a generated protocol buffer package.

It is generated from these files:
	api/about.proto
	api/common.proto
	api/contest_auth.proto
	api/contest_list_problems.proto
	api/contest_list_submissions.proto
	api/contest_ranklist.proto
	api/contest_save.proto
	api/contest_show.proto
	api/edit_problem.proto
	api/language.proto
	api/list_contests.proto
	api/list_problems.proto
	api/list_submissions.proto
	api/login.proto
	api/logout.proto
	api/ojinfo.proto
	api/register.proto
	api/rejudge.proto
	api/save_problem.proto
	api/show_problem.proto
	api/submit.proto
	api/upload_problem.proto
	api/webapi.proto

It has these top-level messages:
	AboutRequest
	AboutResponse
	Error
	ContestAuthRequest
	ContestAuthResponse
	ContestListProblemsRequest
	ContestListProblemsResponse
	ContestListSubmissionsRequest
	ContestListSubmissionsResponse
	ContestRanklistRequest
	RankICPC
	ContestRanklistResponse
	ContestSaveRequest
	ContestSaveResponse
	ContestShowRequest
	Contest
	ContestShowResponse
	EditProblemRequest
	EditProblemResponse
	Language
	ListContestsRequest
	ListContestsResponse
	ListProblemsRequest
	ListProblemsResponse
	ListSubmissionsRequest
	ListSubmissionsResponse
	LoginInitRequest
	LoginInitResponse
	LoginAuthRequest
	LoginAuthResponse
	LogoutRequest
	LogoutResponse
	OJInfo
	RegisterRequest
	RegisterResponse
	ReJudgeRequest
	ReJudgeResponse
	SaveProblemRequest
	SaveProblemResponse
	ShowProblemRequest
	Problem
	ShowProblemResponse
	SubmitRequest
	SubmitResponse
	UploadProblemRequest
	UploadProblemResponse
	WebGetRequest
	WebPostRequest
	WebResponse
*/
package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AboutRequest struct {
	NeedOjsList       bool `protobuf:"varint,1,opt,name=need_ojs_list,json=needOjsList" json:"need_ojs_list,omitempty"`
	NeedLanguagesList bool `protobuf:"varint,2,opt,name=need_languages_list,json=needLanguagesList" json:"need_languages_list,omitempty"`
	NeedUsername      bool `protobuf:"varint,3,opt,name=need_username,json=needUsername" json:"need_username,omitempty"`
}

func (m *AboutRequest) Reset()                    { *m = AboutRequest{} }
func (m *AboutRequest) String() string            { return proto.CompactTextString(m) }
func (*AboutRequest) ProtoMessage()               {}
func (*AboutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AboutRequest) GetNeedOjsList() bool {
	if m != nil {
		return m.NeedOjsList
	}
	return false
}

func (m *AboutRequest) GetNeedLanguagesList() bool {
	if m != nil {
		return m.NeedLanguagesList
	}
	return false
}

func (m *AboutRequest) GetNeedUsername() bool {
	if m != nil {
		return m.NeedUsername
	}
	return false
}

type AboutResponse struct {
	OjsList       []*OJInfo   `protobuf:"bytes,1,rep,name=ojs_list,json=ojsList" json:"ojs_list,omitempty"`
	LanguagesList []*Language `protobuf:"bytes,2,rep,name=languages_list,json=languagesList" json:"languages_list,omitempty"`
	Username      string      `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Error         *Error      `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *AboutResponse) Reset()                    { *m = AboutResponse{} }
func (m *AboutResponse) String() string            { return proto.CompactTextString(m) }
func (*AboutResponse) ProtoMessage()               {}
func (*AboutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AboutResponse) GetOjsList() []*OJInfo {
	if m != nil {
		return m.OjsList
	}
	return nil
}

func (m *AboutResponse) GetLanguagesList() []*Language {
	if m != nil {
		return m.LanguagesList
	}
	return nil
}

func (m *AboutResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AboutResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*AboutRequest)(nil), "api.AboutRequest")
	proto.RegisterType((*AboutResponse)(nil), "api.AboutResponse")
}

func init() { proto.RegisterFile("api/about.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x64, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x14, 0x46, 0x89, 0xf5, 0xa7, 0xde, 0x4e, 0xfd, 0x89, 0x9b, 0xd2, 0x55, 0xa9, 0x20, 0x5d, 0x55,
	0x18, 0x7d, 0x01, 0x17, 0x2e, 0x94, 0x81, 0x81, 0x80, 0xeb, 0x21, 0xa3, 0x99, 0x21, 0xa5, 0xcd,
	0x8d, 0x49, 0xfa, 0x0c, 0x3e, 0x8c, 0x2f, 0x29, 0x49, 0x53, 0x71, 0x70, 0x99, 0x73, 0x0f, 0x1f,
	0x87, 0xc0, 0x25, 0xd7, 0xf2, 0x9e, 0x6f, 0x71, 0x74, 0xad, 0x36, 0xe8, 0x90, 0x26, 0x5c, 0xcb,
	0xf2, 0xca, 0xd3, 0x77, 0x1c, 0x06, 0x54, 0x13, 0x2e, 0xa9, 0x27, 0x3d, 0x57, 0xfb, 0x91, 0xef,
	0x45, 0x64, 0xc1, 0xc2, 0x4e, 0xaa, 0x1d, 0x4e, 0xa4, 0xfe, 0x22, 0xb0, 0x78, 0xf2, 0x63, 0x4c,
	0x7c, 0x8e, 0xc2, 0x3a, 0x5a, 0x43, 0xae, 0x84, 0xf8, 0xd8, 0x60, 0x67, 0x37, 0xbd, 0xb4, 0xae,
	0x20, 0x15, 0x69, 0x52, 0x96, 0x79, 0xb8, 0xee, 0xec, 0x4a, 0x5a, 0x47, 0x5b, 0xb8, 0x09, 0xce,
	0xbc, 0x1e, 0xcd, 0xa3, 0x60, 0x5e, 0xfb, 0xd3, 0x6a, 0xbe, 0x04, 0xff, 0x36, 0x6e, 0x8e, 0x56,
	0x18, 0xc5, 0x07, 0x51, 0x24, 0xc1, 0x5c, 0x78, 0xf8, 0x16, 0x59, 0xfd, 0x4d, 0x20, 0x8f, 0x25,
	0x56, 0xa3, 0xb2, 0x82, 0xde, 0x41, 0xfa, 0xa7, 0x22, 0x69, 0xb2, 0x65, 0xd6, 0x72, 0x2d, 0xdb,
	0xf5, 0xeb, 0x8b, 0xda, 0x21, 0x3b, 0xc3, 0x98, 0xf3, 0x08, 0x17, 0xff, 0x4a, 0xbc, 0x9d, 0x07,
	0x7b, 0x4e, 0x61, 0x79, 0x7f, 0x10, 0x55, 0x42, 0x7a, 0xd0, 0x73, 0xce, 0x7e, 0xdf, 0xb4, 0x82,
	0x13, 0x61, 0x0c, 0x9a, 0xe2, 0xb8, 0x22, 0x4d, 0xb6, 0x84, 0x30, 0xf4, 0xec, 0x09, 0x9b, 0x0e,
	0xdb, 0xd3, 0xf0, 0x7d, 0x0f, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe2, 0x88, 0x2e, 0xb9, 0x8e,
	0x01, 0x00, 0x00,
}
