// Code generated by protoc-gen-go.
// source: api/contest_list_submissions.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ContestListSubmissionsRequest struct {
	PerPage          int32  `protobuf:"varint,1,opt,name=per_page,json=perPage" json:"per_page,omitempty"`
	CurrentPage      int32  `protobuf:"varint,2,opt,name=current_page,json=currentPage" json:"current_page,omitempty"`
	ContestId        int64  `protobuf:"varint,3,opt,name=contest_id,json=contestId" json:"contest_id,omitempty"`
	FilterRunId      int64  `protobuf:"varint,4,opt,name=filter_run_id,json=filterRunId" json:"filter_run_id,omitempty"`
	FilterUsername   string `protobuf:"bytes,5,opt,name=filter_username,json=filterUsername" json:"filter_username,omitempty"`
	FilterLabel      string `protobuf:"bytes,6,opt,name=filter_label,json=filterLabel" json:"filter_label,omitempty"`
	FilterStatusCode string `protobuf:"bytes,7,opt,name=filter_status_code,json=filterStatusCode" json:"filter_status_code,omitempty"`
	FilterLanguage   string `protobuf:"bytes,8,opt,name=filter_language,json=filterLanguage" json:"filter_language,omitempty"`
	FilterCompiler   string `protobuf:"bytes,9,opt,name=filter_compiler,json=filterCompiler" json:"filter_compiler,omitempty"`
	IsDesc           bool   `protobuf:"varint,10,opt,name=is_desc,json=isDesc" json:"is_desc,omitempty"`
}

func (m *ContestListSubmissionsRequest) Reset()                    { *m = ContestListSubmissionsRequest{} }
func (m *ContestListSubmissionsRequest) String() string            { return proto.CompactTextString(m) }
func (*ContestListSubmissionsRequest) ProtoMessage()               {}
func (*ContestListSubmissionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *ContestListSubmissionsRequest) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *ContestListSubmissionsRequest) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *ContestListSubmissionsRequest) GetContestId() int64 {
	if m != nil {
		return m.ContestId
	}
	return 0
}

func (m *ContestListSubmissionsRequest) GetFilterRunId() int64 {
	if m != nil {
		return m.FilterRunId
	}
	return 0
}

func (m *ContestListSubmissionsRequest) GetFilterUsername() string {
	if m != nil {
		return m.FilterUsername
	}
	return ""
}

func (m *ContestListSubmissionsRequest) GetFilterLabel() string {
	if m != nil {
		return m.FilterLabel
	}
	return ""
}

func (m *ContestListSubmissionsRequest) GetFilterStatusCode() string {
	if m != nil {
		return m.FilterStatusCode
	}
	return ""
}

func (m *ContestListSubmissionsRequest) GetFilterLanguage() string {
	if m != nil {
		return m.FilterLanguage
	}
	return ""
}

func (m *ContestListSubmissionsRequest) GetFilterCompiler() string {
	if m != nil {
		return m.FilterCompiler
	}
	return ""
}

func (m *ContestListSubmissionsRequest) GetIsDesc() bool {
	if m != nil {
		return m.IsDesc
	}
	return false
}

type ContestListSubmissionsResponse struct {
	Lines       []*ContestListSubmissionsResponse_PerLine `protobuf:"bytes,1,rep,name=lines" json:"lines,omitempty"`
	TotalLines  int32                                     `protobuf:"varint,2,opt,name=total_lines,json=totalLines" json:"total_lines,omitempty"`
	TotalPages  int32                                     `protobuf:"varint,3,opt,name=total_pages,json=totalPages" json:"total_pages,omitempty"`
	CurrentPage int32                                     `protobuf:"varint,4,opt,name=current_page,json=currentPage" json:"current_page,omitempty"`
	Error       *Error                                    `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
}

func (m *ContestListSubmissionsResponse) Reset()                    { *m = ContestListSubmissionsResponse{} }
func (m *ContestListSubmissionsResponse) String() string            { return proto.CompactTextString(m) }
func (*ContestListSubmissionsResponse) ProtoMessage()               {}
func (*ContestListSubmissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *ContestListSubmissionsResponse) GetLines() []*ContestListSubmissionsResponse_PerLine {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *ContestListSubmissionsResponse) GetTotalLines() int32 {
	if m != nil {
		return m.TotalLines
	}
	return 0
}

func (m *ContestListSubmissionsResponse) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *ContestListSubmissionsResponse) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *ContestListSubmissionsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ContestListSubmissionsResponse_PerLine struct {
	Label           string    `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	RunId           int64     `protobuf:"varint,2,opt,name=run_id,json=runId" json:"run_id,omitempty"`
	Username        string    `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Status          string    `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	StatusCode      string    `protobuf:"bytes,5,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	CeInfo          string    `protobuf:"bytes,6,opt,name=ce_info,json=ceInfo" json:"ce_info,omitempty"`
	Language        *Language `protobuf:"bytes,7,opt,name=language" json:"language,omitempty"`
	TimeUsed        int32     `protobuf:"varint,8,opt,name=time_used,json=timeUsed" json:"time_used,omitempty"`
	MemoryUsed      int32     `protobuf:"varint,9,opt,name=memory_used,json=memoryUsed" json:"memory_used,omitempty"`
	Testcases       int32     `protobuf:"varint,10,opt,name=testcases" json:"testcases,omitempty"`
	TestcasesPassed int32     `protobuf:"varint,11,opt,name=testcases_passed,json=testcasesPassed" json:"testcases_passed,omitempty"`
	CodeLength      int32     `protobuf:"varint,12,opt,name=code_length,json=codeLength" json:"code_length,omitempty"`
	SubmitTime      string    `protobuf:"bytes,13,opt,name=submit_time,json=submitTime" json:"submit_time,omitempty"`
	Code            string    `protobuf:"bytes,14,opt,name=code" json:"code,omitempty"`
	IsSpj           bool      `protobuf:"varint,15,opt,name=is_spj,json=isSpj" json:"is_spj,omitempty"`
}

func (m *ContestListSubmissionsResponse_PerLine) Reset() {
	*m = ContestListSubmissionsResponse_PerLine{}
}
func (m *ContestListSubmissionsResponse_PerLine) String() string { return proto.CompactTextString(m) }
func (*ContestListSubmissionsResponse_PerLine) ProtoMessage()    {}
func (*ContestListSubmissionsResponse_PerLine) Descriptor() ([]byte, []int) {
	return fileDescriptor4, []int{1, 0}
}

func (m *ContestListSubmissionsResponse_PerLine) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *ContestListSubmissionsResponse_PerLine) GetRunId() int64 {
	if m != nil {
		return m.RunId
	}
	return 0
}

func (m *ContestListSubmissionsResponse_PerLine) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ContestListSubmissionsResponse_PerLine) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ContestListSubmissionsResponse_PerLine) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *ContestListSubmissionsResponse_PerLine) GetCeInfo() string {
	if m != nil {
		return m.CeInfo
	}
	return ""
}

func (m *ContestListSubmissionsResponse_PerLine) GetLanguage() *Language {
	if m != nil {
		return m.Language
	}
	return nil
}

func (m *ContestListSubmissionsResponse_PerLine) GetTimeUsed() int32 {
	if m != nil {
		return m.TimeUsed
	}
	return 0
}

func (m *ContestListSubmissionsResponse_PerLine) GetMemoryUsed() int32 {
	if m != nil {
		return m.MemoryUsed
	}
	return 0
}

func (m *ContestListSubmissionsResponse_PerLine) GetTestcases() int32 {
	if m != nil {
		return m.Testcases
	}
	return 0
}

func (m *ContestListSubmissionsResponse_PerLine) GetTestcasesPassed() int32 {
	if m != nil {
		return m.TestcasesPassed
	}
	return 0
}

func (m *ContestListSubmissionsResponse_PerLine) GetCodeLength() int32 {
	if m != nil {
		return m.CodeLength
	}
	return 0
}

func (m *ContestListSubmissionsResponse_PerLine) GetSubmitTime() string {
	if m != nil {
		return m.SubmitTime
	}
	return ""
}

func (m *ContestListSubmissionsResponse_PerLine) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ContestListSubmissionsResponse_PerLine) GetIsSpj() bool {
	if m != nil {
		return m.IsSpj
	}
	return false
}

func init() {
	proto.RegisterType((*ContestListSubmissionsRequest)(nil), "api.ContestListSubmissionsRequest")
	proto.RegisterType((*ContestListSubmissionsResponse)(nil), "api.ContestListSubmissionsResponse")
	proto.RegisterType((*ContestListSubmissionsResponse_PerLine)(nil), "api.ContestListSubmissionsResponse.PerLine")
}

func init() { proto.RegisterFile("api/contest_list_submissions.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x94, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0xba, 0x4e, 0xe2, 0x49, 0xff, 0x69, 0x05, 0xd4, 0x04, 0x0a, 0x21, 0x17, 0x52,
	0x81, 0x82, 0x54, 0x9e, 0x00, 0x15, 0x0e, 0x95, 0x72, 0xa8, 0x5c, 0x7a, 0xb6, 0x5c, 0x7b, 0x1a,
	0xb6, 0xb2, 0x77, 0xcd, 0xce, 0xfa, 0xc0, 0x03, 0xf0, 0x3e, 0xbc, 0x03, 0x2f, 0x86, 0x76, 0x76,
	0xf3, 0x07, 0x55, 0x70, 0xcb, 0xfe, 0xe6, 0xf3, 0xec, 0xec, 0x7c, 0x9f, 0x02, 0xb3, 0xb2, 0x93,
	0x1f, 0x2a, 0xad, 0x2c, 0x92, 0x2d, 0x1a, 0x49, 0xb6, 0xa0, 0xfe, 0xae, 0x95, 0x44, 0x52, 0x2b,
	0x5a, 0x74, 0x46, 0x5b, 0x2d, 0xe2, 0xb2, 0x93, 0x93, 0x13, 0x2f, 0x6c, 0x5b, 0xad, 0x3c, 0x9e,
	0x08, 0x47, 0x9a, 0x52, 0xad, 0xfa, 0x72, 0x85, 0x9e, 0xcd, 0x7e, 0xc6, 0x70, 0x76, 0xe9, 0xbb,
	0x2d, 0x25, 0xd9, 0x9b, 0x6d, 0xaf, 0x1c, 0xbf, 0xf7, 0x48, 0x56, 0x3c, 0x87, 0x51, 0x87, 0xa6,
	0xe8, 0xca, 0x15, 0x66, 0xd1, 0x34, 0x9a, 0x27, 0xf9, 0xb0, 0x43, 0x73, 0x5d, 0xae, 0x50, 0xbc,
	0x81, 0x83, 0xaa, 0x37, 0x06, 0x95, 0xf5, 0xe5, 0x3d, 0x2e, 0x8f, 0x03, 0x63, 0xc9, 0x19, 0xc0,
	0x7a, 0x58, 0x59, 0x67, 0xf1, 0x34, 0x9a, 0xc7, 0x79, 0x1a, 0xc8, 0x55, 0x2d, 0x66, 0x70, 0x78,
	0x2f, 0x1b, 0x8b, 0xa6, 0x30, 0xbd, 0x72, 0x8a, 0x7d, 0x56, 0x8c, 0x3d, 0xcc, 0x7b, 0x75, 0x55,
	0x8b, 0xb7, 0x70, 0x1c, 0x34, 0x3d, 0xa1, 0x51, 0x65, 0x8b, 0x59, 0x32, 0x8d, 0xe6, 0x69, 0x7e,
	0xe4, 0xf1, 0x6d, 0xa0, 0x6e, 0x9c, 0x20, 0x6c, 0xca, 0x3b, 0x6c, 0xb2, 0x01, 0xab, 0x42, 0xaf,
	0xa5, 0x43, 0xe2, 0x3d, 0x88, 0x20, 0x21, 0x5b, 0xda, 0x9e, 0x8a, 0x4a, 0xd7, 0x98, 0x0d, 0x59,
	0x78, 0xe2, 0x2b, 0x37, 0x5c, 0xb8, 0xd4, 0x35, 0xee, 0xdc, 0xbc, 0xde, 0x5a, 0x36, 0xda, 0xbd,
	0x79, 0x19, 0xe8, 0x8e, 0xb0, 0xd2, 0x6d, 0x27, 0x1b, 0x34, 0x59, 0xba, 0x2b, 0xbc, 0x0c, 0x54,
	0x9c, 0xc2, 0x50, 0x52, 0x51, 0x23, 0x55, 0x19, 0x4c, 0xa3, 0xf9, 0x28, 0x1f, 0x48, 0xfa, 0x8c,
	0x54, 0xcd, 0x7e, 0x25, 0xf0, 0xea, 0x5f, 0x3e, 0x50, 0xa7, 0x15, 0xa1, 0xf8, 0x04, 0x49, 0x23,
	0x15, 0x52, 0x16, 0x4d, 0xe3, 0xf9, 0xf8, 0xe2, 0xdd, 0xa2, 0xec, 0xe4, 0xe2, 0xff, 0xdf, 0x2c,
	0xae, 0xd1, 0x2c, 0xa5, 0xc2, 0xdc, 0x7f, 0x29, 0x5e, 0xc3, 0xd8, 0x6a, 0x5b, 0x36, 0x85, 0x6f,
	0xe4, 0xfd, 0x02, 0x46, 0xcb, 0xbf, 0x05, 0xce, 0x4f, 0x62, 0xbf, 0xd6, 0x02, 0x67, 0x27, 0x3d,
	0xb2, 0x7c, 0xff, 0xb1, 0xe5, 0x53, 0x48, 0xd0, 0x18, 0x6d, 0xd8, 0xa5, 0xf1, 0x05, 0xf0, 0x9c,
	0x5f, 0x1c, 0xc9, 0x7d, 0x61, 0xf2, 0x3b, 0x86, 0x61, 0x98, 0x4c, 0x3c, 0x81, 0xc4, 0xbb, 0x15,
	0xf1, 0xc2, 0xfc, 0x41, 0x3c, 0x85, 0x41, 0x08, 0xc4, 0x1e, 0x07, 0x22, 0x31, 0x1c, 0x85, 0x09,
	0x8c, 0x36, 0x19, 0x88, 0x59, 0xbf, 0x39, 0x8b, 0x67, 0x30, 0xf0, 0x9e, 0xf2, 0x4c, 0x69, 0x1e,
	0x4e, 0xee, 0x49, 0xbb, 0x5e, 0xfb, 0xe8, 0x00, 0x6d, 0x5d, 0x3e, 0x85, 0x61, 0x85, 0x85, 0x54,
	0xf7, 0x3a, 0x24, 0x66, 0x50, 0xe1, 0x95, 0xba, 0xd7, 0xe2, 0x1c, 0x46, 0x1b, 0xdf, 0x87, 0xfc,
	0x96, 0x43, 0x7e, 0xcb, 0xda, 0xf6, 0x7c, 0x53, 0x16, 0x2f, 0x20, 0xb5, 0xb2, 0x45, 0x97, 0xd0,
	0x9a, 0x33, 0x92, 0xe4, 0x23, 0x07, 0x6e, 0x09, 0x6b, 0x37, 0x41, 0x8b, 0xad, 0x36, 0x3f, 0x7c,
	0x39, 0xf5, 0x4b, 0xf5, 0x88, 0x05, 0x2f, 0x21, 0x75, 0x26, 0x56, 0x25, 0x21, 0x71, 0x2e, 0x92,
	0x7c, 0x0b, 0xc4, 0x39, 0x9c, 0x6c, 0x0e, 0x45, 0x57, 0x92, 0xeb, 0x31, 0x66, 0xd1, 0xf1, 0x86,
	0x5f, 0x33, 0x76, 0x37, 0xb9, 0x47, 0x16, 0x0d, 0xaa, 0x95, 0xfd, 0x96, 0x1d, 0xf8, 0x9b, 0x1c,
	0x5a, 0x32, 0xe1, 0x65, 0xb8, 0x98, 0xd8, 0xc2, 0x4d, 0x97, 0x1d, 0x86, 0x65, 0x30, 0xfa, 0x2a,
	0x5b, 0x14, 0x02, 0xf6, 0x79, 0x4d, 0x47, 0x5c, 0xe1, 0xdf, 0xce, 0x0c, 0x49, 0x05, 0x75, 0x0f,
	0xd9, 0x31, 0x67, 0x36, 0x91, 0x74, 0xd3, 0x3d, 0xdc, 0x0d, 0xf8, 0x1f, 0xe4, 0xe3, 0x9f, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x56, 0xf4, 0xa7, 0x3c, 0x92, 0x04, 0x00, 0x00,
}
