// Code generated by protoc-gen-go.
// source: api/list_submissions.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type ListSubmissionsRequest struct {
	PerPage          int32  `protobuf:"varint,1,opt,name=per_page,json=perPage" json:"per_page,omitempty"`
	CurrentPage      int32  `protobuf:"varint,2,opt,name=current_page,json=currentPage" json:"current_page,omitempty"`
	FilterUsername   string `protobuf:"bytes,3,opt,name=filter_username,json=filterUsername" json:"filter_username,omitempty"`
	FilterOj         string `protobuf:"bytes,4,opt,name=filter_oj,json=filterOj" json:"filter_oj,omitempty"`
	FilterPid        string `protobuf:"bytes,5,opt,name=filter_pid,json=filterPid" json:"filter_pid,omitempty"`
	FilterStatusCode string `protobuf:"bytes,6,opt,name=filter_status_code,json=filterStatusCode" json:"filter_status_code,omitempty"`
	FilterLanguage   string `protobuf:"bytes,7,opt,name=filter_language,json=filterLanguage" json:"filter_language,omitempty"`
	FilterCompiler   string `protobuf:"bytes,8,opt,name=filter_compiler,json=filterCompiler" json:"filter_compiler,omitempty"`
}

func (m *ListSubmissionsRequest) Reset()                    { *m = ListSubmissionsRequest{} }
func (m *ListSubmissionsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListSubmissionsRequest) ProtoMessage()               {}
func (*ListSubmissionsRequest) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{0} }

func (m *ListSubmissionsRequest) GetPerPage() int32 {
	if m != nil {
		return m.PerPage
	}
	return 0
}

func (m *ListSubmissionsRequest) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *ListSubmissionsRequest) GetFilterUsername() string {
	if m != nil {
		return m.FilterUsername
	}
	return ""
}

func (m *ListSubmissionsRequest) GetFilterOj() string {
	if m != nil {
		return m.FilterOj
	}
	return ""
}

func (m *ListSubmissionsRequest) GetFilterPid() string {
	if m != nil {
		return m.FilterPid
	}
	return ""
}

func (m *ListSubmissionsRequest) GetFilterStatusCode() string {
	if m != nil {
		return m.FilterStatusCode
	}
	return ""
}

func (m *ListSubmissionsRequest) GetFilterLanguage() string {
	if m != nil {
		return m.FilterLanguage
	}
	return ""
}

func (m *ListSubmissionsRequest) GetFilterCompiler() string {
	if m != nil {
		return m.FilterCompiler
	}
	return ""
}

type ListSubmissionsResponse struct {
	Lines       []*ListSubmissionsResponse_PerLine `protobuf:"bytes,1,rep,name=lines" json:"lines,omitempty"`
	TotalLines  int32                              `protobuf:"varint,2,opt,name=total_lines,json=totalLines" json:"total_lines,omitempty"`
	TotalPages  int32                              `protobuf:"varint,3,opt,name=total_pages,json=totalPages" json:"total_pages,omitempty"`
	CurrentPage int32                              `protobuf:"varint,4,opt,name=current_page,json=currentPage" json:"current_page,omitempty"`
	Error       *Error                             `protobuf:"bytes,5,opt,name=error" json:"error,omitempty"`
}

func (m *ListSubmissionsResponse) Reset()                    { *m = ListSubmissionsResponse{} }
func (m *ListSubmissionsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListSubmissionsResponse) ProtoMessage()               {}
func (*ListSubmissionsResponse) Descriptor() ([]byte, []int) { return fileDescriptor6, []int{1} }

func (m *ListSubmissionsResponse) GetLines() []*ListSubmissionsResponse_PerLine {
	if m != nil {
		return m.Lines
	}
	return nil
}

func (m *ListSubmissionsResponse) GetTotalLines() int32 {
	if m != nil {
		return m.TotalLines
	}
	return 0
}

func (m *ListSubmissionsResponse) GetTotalPages() int32 {
	if m != nil {
		return m.TotalPages
	}
	return 0
}

func (m *ListSubmissionsResponse) GetCurrentPage() int32 {
	if m != nil {
		return m.CurrentPage
	}
	return 0
}

func (m *ListSubmissionsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type ListSubmissionsResponse_PerLine struct {
	Sid             string    `protobuf:"bytes,1,opt,name=sid" json:"sid,omitempty"`
	RunId           int64     `protobuf:"varint,2,opt,name=run_id,json=runId" json:"run_id,omitempty"`
	Username        string    `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Status          string    `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	StatusCode      string    `protobuf:"bytes,5,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	CeInfo          string    `protobuf:"bytes,6,opt,name=ce_info,json=ceInfo" json:"ce_info,omitempty"`
	Language        *Language `protobuf:"bytes,7,opt,name=language" json:"language,omitempty"`
	TimeUsed        int32     `protobuf:"varint,8,opt,name=time_used,json=timeUsed" json:"time_used,omitempty"`
	MemoryUsed      int32     `protobuf:"varint,9,opt,name=memory_used,json=memoryUsed" json:"memory_used,omitempty"`
	Testcases       int32     `protobuf:"varint,10,opt,name=testcases" json:"testcases,omitempty"`
	TestcasesPassed int32     `protobuf:"varint,11,opt,name=testcases_passed,json=testcasesPassed" json:"testcases_passed,omitempty"`
	CodeLength      int32     `protobuf:"varint,12,opt,name=code_length,json=codeLength" json:"code_length,omitempty"`
	SubmitTime      string    `protobuf:"bytes,13,opt,name=submit_time,json=submitTime" json:"submit_time,omitempty"`
	Code            string    `protobuf:"bytes,14,opt,name=code" json:"code,omitempty"`
	IsSpj           bool      `protobuf:"varint,15,opt,name=is_spj,json=isSpj" json:"is_spj,omitempty"`
}

func (m *ListSubmissionsResponse_PerLine) Reset()         { *m = ListSubmissionsResponse_PerLine{} }
func (m *ListSubmissionsResponse_PerLine) String() string { return proto.CompactTextString(m) }
func (*ListSubmissionsResponse_PerLine) ProtoMessage()    {}
func (*ListSubmissionsResponse_PerLine) Descriptor() ([]byte, []int) {
	return fileDescriptor6, []int{1, 0}
}

func (m *ListSubmissionsResponse_PerLine) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *ListSubmissionsResponse_PerLine) GetRunId() int64 {
	if m != nil {
		return m.RunId
	}
	return 0
}

func (m *ListSubmissionsResponse_PerLine) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ListSubmissionsResponse_PerLine) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *ListSubmissionsResponse_PerLine) GetStatusCode() string {
	if m != nil {
		return m.StatusCode
	}
	return ""
}

func (m *ListSubmissionsResponse_PerLine) GetCeInfo() string {
	if m != nil {
		return m.CeInfo
	}
	return ""
}

func (m *ListSubmissionsResponse_PerLine) GetLanguage() *Language {
	if m != nil {
		return m.Language
	}
	return nil
}

func (m *ListSubmissionsResponse_PerLine) GetTimeUsed() int32 {
	if m != nil {
		return m.TimeUsed
	}
	return 0
}

func (m *ListSubmissionsResponse_PerLine) GetMemoryUsed() int32 {
	if m != nil {
		return m.MemoryUsed
	}
	return 0
}

func (m *ListSubmissionsResponse_PerLine) GetTestcases() int32 {
	if m != nil {
		return m.Testcases
	}
	return 0
}

func (m *ListSubmissionsResponse_PerLine) GetTestcasesPassed() int32 {
	if m != nil {
		return m.TestcasesPassed
	}
	return 0
}

func (m *ListSubmissionsResponse_PerLine) GetCodeLength() int32 {
	if m != nil {
		return m.CodeLength
	}
	return 0
}

func (m *ListSubmissionsResponse_PerLine) GetSubmitTime() string {
	if m != nil {
		return m.SubmitTime
	}
	return ""
}

func (m *ListSubmissionsResponse_PerLine) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ListSubmissionsResponse_PerLine) GetIsSpj() bool {
	if m != nil {
		return m.IsSpj
	}
	return false
}

func init() {
	proto.RegisterType((*ListSubmissionsRequest)(nil), "api.ListSubmissionsRequest")
	proto.RegisterType((*ListSubmissionsResponse)(nil), "api.ListSubmissionsResponse")
	proto.RegisterType((*ListSubmissionsResponse_PerLine)(nil), "api.ListSubmissionsResponse.PerLine")
}

func init() { proto.RegisterFile("api/list_submissions.proto", fileDescriptor6) }

var fileDescriptor6 = []byte{
	// 559 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x93, 0x5f, 0x6f, 0xd3, 0x3c,
	0x14, 0xc6, 0xd5, 0x75, 0x69, 0xd3, 0xd3, 0xfd, 0xa9, 0x2c, 0xbd, 0x5b, 0xde, 0x02, 0xa2, 0x4c,
	0x48, 0x74, 0x12, 0x2a, 0xd2, 0xb8, 0xe3, 0x76, 0xe2, 0x62, 0x52, 0x25, 0xaa, 0x8c, 0x5d, 0x47,
	0x59, 0x72, 0x56, 0x5c, 0x25, 0xb6, 0xf1, 0x71, 0x2e, 0xf8, 0x32, 0x7c, 0x11, 0x2e, 0xf8, 0x6a,
	0xc8, 0xc7, 0x5e, 0xd7, 0x51, 0x71, 0x17, 0xff, 0x9e, 0x27, 0xce, 0xf1, 0xf3, 0x38, 0x30, 0x2d,
	0x8d, 0xfc, 0xd0, 0x48, 0x72, 0x05, 0x75, 0xf7, 0xad, 0x24, 0x92, 0x5a, 0xd1, 0xc2, 0x58, 0xed,
	0xb4, 0xe8, 0x97, 0x46, 0x4e, 0x27, 0xde, 0x50, 0xe9, 0xb6, 0xd5, 0x2a, 0xe0, 0xa9, 0xe0, 0x57,
	0x4a, 0xb5, 0xee, 0xca, 0x35, 0x06, 0x76, 0xf1, 0xeb, 0x00, 0xce, 0x96, 0x92, 0xdc, 0xed, 0xd3,
	0x26, 0x39, 0x7e, 0xef, 0x90, 0x9c, 0xf8, 0x1f, 0x52, 0x83, 0xb6, 0x30, 0xe5, 0x1a, 0xb3, 0xde,
	0xac, 0x37, 0x4f, 0xf2, 0xa1, 0x41, 0xbb, 0x2a, 0xd7, 0x28, 0xde, 0xc0, 0x51, 0xd5, 0x59, 0x8b,
	0xca, 0x05, 0xf9, 0x80, 0xe5, 0x71, 0x64, 0x6c, 0x79, 0x07, 0xa7, 0x0f, 0xb2, 0x71, 0x68, 0x8b,
	0x8e, 0xd0, 0xaa, 0xb2, 0xc5, 0xac, 0x3f, 0xeb, 0xcd, 0x47, 0xf9, 0x49, 0xc0, 0x77, 0x91, 0x8a,
	0x17, 0x30, 0x8a, 0x46, 0xbd, 0xc9, 0x0e, 0xd9, 0x92, 0x06, 0xf0, 0x65, 0x23, 0x5e, 0x01, 0x44,
	0xd1, 0xc8, 0x3a, 0x4b, 0x58, 0x8d, 0xf6, 0x95, 0xac, 0xc5, 0x7b, 0x10, 0x51, 0x26, 0x57, 0xba,
	0x8e, 0x8a, 0x4a, 0xd7, 0x98, 0x0d, 0xd8, 0x36, 0x09, 0xca, 0x2d, 0x0b, 0xd7, 0xba, 0xde, 0x1d,
	0xe9, 0x31, 0x84, 0x6c, 0xb8, 0x3b, 0xd2, 0x32, 0xd2, 0x1d, 0x63, 0xa5, 0x5b, 0x23, 0x1b, 0xb4,
	0x59, 0xba, 0x6b, 0xbc, 0x8e, 0xf4, 0xe2, 0x67, 0x02, 0xe7, 0x7b, 0xe9, 0x91, 0xd1, 0x8a, 0x50,
	0x7c, 0x82, 0xa4, 0x91, 0x0a, 0x29, 0xeb, 0xcd, 0xfa, 0xf3, 0xf1, 0xd5, 0xdb, 0x45, 0x69, 0xe4,
	0xe2, 0x1f, 0xe6, 0xc5, 0x0a, 0xed, 0x52, 0x2a, 0xcc, 0xc3, 0x2b, 0xe2, 0x35, 0x8c, 0x9d, 0x76,
	0x65, 0x53, 0x84, 0x1d, 0x42, 0xbc, 0xc0, 0x68, 0xf9, 0xdc, 0xe0, 0xe3, 0x27, 0x4e, 0xf6, 0xd1,
	0xe0, 0xd3, 0xa7, 0xbd, 0x86, 0x0e, 0xf7, 0x1b, 0x9a, 0x41, 0x82, 0xd6, 0x6a, 0xcb, 0xb1, 0x8e,
	0xaf, 0x80, 0x07, 0xfc, 0xec, 0x49, 0x1e, 0x84, 0xe9, 0xef, 0x3e, 0x0c, 0xe3, 0x64, 0x62, 0x02,
	0x7d, 0x92, 0x35, 0x5f, 0x84, 0x51, 0xee, 0x1f, 0xc5, 0x7f, 0x30, 0xb0, 0x9d, 0x2a, 0x64, 0xcd,
	0xf3, 0xf5, 0xf3, 0xc4, 0x76, 0xea, 0xa6, 0x16, 0x53, 0x48, 0xff, 0x6a, 0x7c, 0xbb, 0x16, 0x67,
	0x30, 0x08, 0x45, 0xc5, 0xa2, 0xe3, 0xca, 0x1f, 0x67, 0xb7, 0xc0, 0xd0, 0x33, 0xd0, 0x53, 0x75,
	0xe7, 0x30, 0xac, 0xb0, 0x90, 0xea, 0x41, 0xc7, 0x76, 0x07, 0x15, 0xde, 0xa8, 0x07, 0x2d, 0x2e,
	0x21, 0x7d, 0x56, 0xe6, 0xf8, 0xea, 0x38, 0x04, 0x1d, 0x61, 0xbe, 0x95, 0xfd, 0x45, 0x73, 0xb2,
	0x45, 0x7f, 0x1f, 0x6b, 0xee, 0x33, 0xc9, 0x53, 0x0f, 0xee, 0x08, 0x6b, 0x3f, 0x41, 0x8b, 0xad,
	0xb6, 0x3f, 0x82, 0x3c, 0x0a, 0x81, 0x06, 0xc4, 0x86, 0x97, 0x30, 0x72, 0x48, 0xae, 0x2a, 0x09,
	0x29, 0x03, 0x96, 0x9f, 0x80, 0xb8, 0x84, 0xc9, 0x76, 0x51, 0x98, 0x92, 0xfc, 0x1e, 0x63, 0x36,
	0x9d, 0x6e, 0xf9, 0x8a, 0xb1, 0xff, 0x92, 0x3f, 0x64, 0xd1, 0xa0, 0x5a, 0xbb, 0x6f, 0xd9, 0x51,
	0xf8, 0x92, 0x47, 0x4b, 0x26, 0x1c, 0x86, 0xbf, 0x22, 0xae, 0xf0, 0xd3, 0x65, 0xc7, 0x31, 0x0c,
	0x46, 0x5f, 0x65, 0x8b, 0x42, 0xc0, 0x21, 0xc7, 0x74, 0xc2, 0x0a, 0x3f, 0xfb, 0x32, 0x24, 0x15,
	0x64, 0x36, 0xd9, 0xe9, 0xac, 0x37, 0x4f, 0xf3, 0x44, 0xd2, 0xad, 0xd9, 0xdc, 0x0f, 0xf8, 0x2f,
	0xff, 0xf8, 0x27, 0x00, 0x00, 0xff, 0xff, 0xfa, 0x2b, 0xa3, 0x5d, 0x2e, 0x04, 0x00, 0x00,
}
