// Code generated by protoc-gen-go.
// source: api/webapi.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type WebGetRequest struct {
	ListProblemsRequest           *ListProblemsRequest           `protobuf:"bytes,1,opt,name=list_problems_request,json=listProblemsRequest" json:"list_problems_request,omitempty"`
	ListSubmissionsRequest        *ListSubmissionsRequest        `protobuf:"bytes,2,opt,name=list_submissions_request,json=listSubmissionsRequest" json:"list_submissions_request,omitempty"`
	ListContestsRequest           *ListContestsRequest           `protobuf:"bytes,3,opt,name=list_contests_request,json=listContestsRequest" json:"list_contests_request,omitempty"`
	ShowProblemRequest            *ShowProblemRequest            `protobuf:"bytes,4,opt,name=show_problem_request,json=showProblemRequest" json:"show_problem_request,omitempty"`
	AboutRequest                  *AboutRequest                  `protobuf:"bytes,5,opt,name=about_request,json=aboutRequest" json:"about_request,omitempty"`
	ContestShowRequest            *ContestShowRequest            `protobuf:"bytes,6,opt,name=contest_show_request,json=contestShowRequest" json:"contest_show_request,omitempty"`
	ContestListProblemsRequest    *ContestListProblemsRequest    `protobuf:"bytes,7,opt,name=contest_list_problems_request,json=contestListProblemsRequest" json:"contest_list_problems_request,omitempty"`
	ContestListSubmissionsRequest *ContestListSubmissionsRequest `protobuf:"bytes,8,opt,name=contest_list_submissions_request,json=contestListSubmissionsRequest" json:"contest_list_submissions_request,omitempty"`
	ContestRanklistRequest        *ContestRanklistRequest        `protobuf:"bytes,9,opt,name=contest_ranklist_request,json=contestRanklistRequest" json:"contest_ranklist_request,omitempty"`
}

func (m *WebGetRequest) Reset()                    { *m = WebGetRequest{} }
func (m *WebGetRequest) String() string            { return proto.CompactTextString(m) }
func (*WebGetRequest) ProtoMessage()               {}
func (*WebGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{0} }

func (m *WebGetRequest) GetListProblemsRequest() *ListProblemsRequest {
	if m != nil {
		return m.ListProblemsRequest
	}
	return nil
}

func (m *WebGetRequest) GetListSubmissionsRequest() *ListSubmissionsRequest {
	if m != nil {
		return m.ListSubmissionsRequest
	}
	return nil
}

func (m *WebGetRequest) GetListContestsRequest() *ListContestsRequest {
	if m != nil {
		return m.ListContestsRequest
	}
	return nil
}

func (m *WebGetRequest) GetShowProblemRequest() *ShowProblemRequest {
	if m != nil {
		return m.ShowProblemRequest
	}
	return nil
}

func (m *WebGetRequest) GetAboutRequest() *AboutRequest {
	if m != nil {
		return m.AboutRequest
	}
	return nil
}

func (m *WebGetRequest) GetContestShowRequest() *ContestShowRequest {
	if m != nil {
		return m.ContestShowRequest
	}
	return nil
}

func (m *WebGetRequest) GetContestListProblemsRequest() *ContestListProblemsRequest {
	if m != nil {
		return m.ContestListProblemsRequest
	}
	return nil
}

func (m *WebGetRequest) GetContestListSubmissionsRequest() *ContestListSubmissionsRequest {
	if m != nil {
		return m.ContestListSubmissionsRequest
	}
	return nil
}

func (m *WebGetRequest) GetContestRanklistRequest() *ContestRanklistRequest {
	if m != nil {
		return m.ContestRanklistRequest
	}
	return nil
}

// WebRequest are all POST requests
type WebPostRequest struct {
	CsrfToken          string              `protobuf:"bytes,1,opt,name=csrf_token,json=csrfToken" json:"csrf_token,omitempty"`
	Captcha            string              `protobuf:"bytes,2,opt,name=captcha" json:"captcha,omitempty"`
	LoginInitRequest   *LoginInitRequest   `protobuf:"bytes,3,opt,name=login_init_request,json=loginInitRequest" json:"login_init_request,omitempty"`
	LoginAuthRequest   *LoginAuthRequest   `protobuf:"bytes,4,opt,name=login_auth_request,json=loginAuthRequest" json:"login_auth_request,omitempty"`
	RegisterRequest    *RegisterRequest    `protobuf:"bytes,5,opt,name=register_request,json=registerRequest" json:"register_request,omitempty"`
	SubmitRequest      *SubmitRequest      `protobuf:"bytes,6,opt,name=submit_request,json=submitRequest" json:"submit_request,omitempty"`
	LogoutRequest      *LogoutRequest      `protobuf:"bytes,7,opt,name=logout_request,json=logoutRequest" json:"logout_request,omitempty"`
	ContestSaveRequest *ContestSaveRequest `protobuf:"bytes,8,opt,name=contest_save_request,json=contestSaveRequest" json:"contest_save_request,omitempty"`
	ContestAuthRequest *ContestAuthRequest `protobuf:"bytes,9,opt,name=contest_auth_request,json=contestAuthRequest" json:"contest_auth_request,omitempty"`
}

func (m *WebPostRequest) Reset()                    { *m = WebPostRequest{} }
func (m *WebPostRequest) String() string            { return proto.CompactTextString(m) }
func (*WebPostRequest) ProtoMessage()               {}
func (*WebPostRequest) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{1} }

func (m *WebPostRequest) GetCsrfToken() string {
	if m != nil {
		return m.CsrfToken
	}
	return ""
}

func (m *WebPostRequest) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

func (m *WebPostRequest) GetLoginInitRequest() *LoginInitRequest {
	if m != nil {
		return m.LoginInitRequest
	}
	return nil
}

func (m *WebPostRequest) GetLoginAuthRequest() *LoginAuthRequest {
	if m != nil {
		return m.LoginAuthRequest
	}
	return nil
}

func (m *WebPostRequest) GetRegisterRequest() *RegisterRequest {
	if m != nil {
		return m.RegisterRequest
	}
	return nil
}

func (m *WebPostRequest) GetSubmitRequest() *SubmitRequest {
	if m != nil {
		return m.SubmitRequest
	}
	return nil
}

func (m *WebPostRequest) GetLogoutRequest() *LogoutRequest {
	if m != nil {
		return m.LogoutRequest
	}
	return nil
}

func (m *WebPostRequest) GetContestSaveRequest() *ContestSaveRequest {
	if m != nil {
		return m.ContestSaveRequest
	}
	return nil
}

func (m *WebPostRequest) GetContestAuthRequest() *ContestAuthRequest {
	if m != nil {
		return m.ContestAuthRequest
	}
	return nil
}

type WebResponse struct {
	SetCsrfToken                   string                          `protobuf:"bytes,1,opt,name=set_csrf_token,json=setCsrfToken" json:"set_csrf_token,omitempty"`
	CaptchaUrl                     string                          `protobuf:"bytes,2,opt,name=captcha_url,json=captchaUrl" json:"captcha_url,omitempty"`
	ListProblemsResponse           *ListProblemsResponse           `protobuf:"bytes,3,opt,name=list_problems_response,json=listProblemsResponse" json:"list_problems_response,omitempty"`
	ListSubmissionsResponse        *ListSubmissionsResponse        `protobuf:"bytes,4,opt,name=list_submissions_response,json=listSubmissionsResponse" json:"list_submissions_response,omitempty"`
	ListContestsResponse           *ListContestsResponse           `protobuf:"bytes,5,opt,name=list_contests_response,json=listContestsResponse" json:"list_contests_response,omitempty"`
	LoginInitResponse              *LoginInitResponse              `protobuf:"bytes,6,opt,name=login_init_response,json=loginInitResponse" json:"login_init_response,omitempty"`
	LoginAuthResponse              *LoginAuthResponse              `protobuf:"bytes,7,opt,name=login_auth_response,json=loginAuthResponse" json:"login_auth_response,omitempty"`
	RegisterResponse               *RegisterResponse               `protobuf:"bytes,8,opt,name=register_response,json=registerResponse" json:"register_response,omitempty"`
	ShowProblemResponse            *ShowProblemResponse            `protobuf:"bytes,9,opt,name=show_problem_response,json=showProblemResponse" json:"show_problem_response,omitempty"`
	SubmitResponse                 *SubmitResponse                 `protobuf:"bytes,10,opt,name=submit_response,json=submitResponse" json:"submit_response,omitempty"`
	AboutResponse                  *AboutResponse                  `protobuf:"bytes,11,opt,name=about_response,json=aboutResponse" json:"about_response,omitempty"`
	LogoutResponse                 *LogoutResponse                 `protobuf:"bytes,12,opt,name=logout_response,json=logoutResponse" json:"logout_response,omitempty"`
	ContestShowResponse            *ContestShowResponse            `protobuf:"bytes,13,opt,name=contest_show_response,json=contestShowResponse" json:"contest_show_response,omitempty"`
	ContestSaveResponse            *ContestSaveResponse            `protobuf:"bytes,14,opt,name=contest_save_response,json=contestSaveResponse" json:"contest_save_response,omitempty"`
	ContestListProblemsResponse    *ContestListProblemsResponse    `protobuf:"bytes,15,opt,name=contest_list_problems_response,json=contestListProblemsResponse" json:"contest_list_problems_response,omitempty"`
	ContestAuthResponse            *ContestAuthResponse            `protobuf:"bytes,16,opt,name=contest_auth_response,json=contestAuthResponse" json:"contest_auth_response,omitempty"`
	ContestListSubmissionsResponse *ContestListSubmissionsResponse `protobuf:"bytes,17,opt,name=contest_list_submissions_response,json=contestListSubmissionsResponse" json:"contest_list_submissions_response,omitempty"`
	ContestRanklistResponse        *ContestRanklistResponse        `protobuf:"bytes,18,opt,name=contest_ranklist_response,json=contestRanklistResponse" json:"contest_ranklist_response,omitempty"`
	Error                          *Error                          `protobuf:"bytes,19,opt,name=error" json:"error,omitempty"`
}

func (m *WebResponse) Reset()                    { *m = WebResponse{} }
func (m *WebResponse) String() string            { return proto.CompactTextString(m) }
func (*WebResponse) ProtoMessage()               {}
func (*WebResponse) Descriptor() ([]byte, []int) { return fileDescriptor20, []int{2} }

func (m *WebResponse) GetSetCsrfToken() string {
	if m != nil {
		return m.SetCsrfToken
	}
	return ""
}

func (m *WebResponse) GetCaptchaUrl() string {
	if m != nil {
		return m.CaptchaUrl
	}
	return ""
}

func (m *WebResponse) GetListProblemsResponse() *ListProblemsResponse {
	if m != nil {
		return m.ListProblemsResponse
	}
	return nil
}

func (m *WebResponse) GetListSubmissionsResponse() *ListSubmissionsResponse {
	if m != nil {
		return m.ListSubmissionsResponse
	}
	return nil
}

func (m *WebResponse) GetListContestsResponse() *ListContestsResponse {
	if m != nil {
		return m.ListContestsResponse
	}
	return nil
}

func (m *WebResponse) GetLoginInitResponse() *LoginInitResponse {
	if m != nil {
		return m.LoginInitResponse
	}
	return nil
}

func (m *WebResponse) GetLoginAuthResponse() *LoginAuthResponse {
	if m != nil {
		return m.LoginAuthResponse
	}
	return nil
}

func (m *WebResponse) GetRegisterResponse() *RegisterResponse {
	if m != nil {
		return m.RegisterResponse
	}
	return nil
}

func (m *WebResponse) GetShowProblemResponse() *ShowProblemResponse {
	if m != nil {
		return m.ShowProblemResponse
	}
	return nil
}

func (m *WebResponse) GetSubmitResponse() *SubmitResponse {
	if m != nil {
		return m.SubmitResponse
	}
	return nil
}

func (m *WebResponse) GetAboutResponse() *AboutResponse {
	if m != nil {
		return m.AboutResponse
	}
	return nil
}

func (m *WebResponse) GetLogoutResponse() *LogoutResponse {
	if m != nil {
		return m.LogoutResponse
	}
	return nil
}

func (m *WebResponse) GetContestShowResponse() *ContestShowResponse {
	if m != nil {
		return m.ContestShowResponse
	}
	return nil
}

func (m *WebResponse) GetContestSaveResponse() *ContestSaveResponse {
	if m != nil {
		return m.ContestSaveResponse
	}
	return nil
}

func (m *WebResponse) GetContestListProblemsResponse() *ContestListProblemsResponse {
	if m != nil {
		return m.ContestListProblemsResponse
	}
	return nil
}

func (m *WebResponse) GetContestAuthResponse() *ContestAuthResponse {
	if m != nil {
		return m.ContestAuthResponse
	}
	return nil
}

func (m *WebResponse) GetContestListSubmissionsResponse() *ContestListSubmissionsResponse {
	if m != nil {
		return m.ContestListSubmissionsResponse
	}
	return nil
}

func (m *WebResponse) GetContestRanklistResponse() *ContestRanklistResponse {
	if m != nil {
		return m.ContestRanklistResponse
	}
	return nil
}

func (m *WebResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*WebGetRequest)(nil), "api.WebGetRequest")
	proto.RegisterType((*WebPostRequest)(nil), "api.WebPostRequest")
	proto.RegisterType((*WebResponse)(nil), "api.WebResponse")
}

func init() { proto.RegisterFile("api/webapi.proto", fileDescriptor20) }

var fileDescriptor20 = []byte{
	// 898 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x96, 0xdf, 0x4e, 0x1b, 0x39,
	0x14, 0xc6, 0xc5, 0x42, 0x80, 0x38, 0xe4, 0x9f, 0x03, 0x21, 0x84, 0x05, 0xb2, 0xd9, 0xbd, 0xd8,
	0x2b, 0x56, 0xda, 0x4a, 0x95, 0x2a, 0x55, 0xaa, 0x28, 0x6a, 0x2b, 0x24, 0xa4, 0xa2, 0xa1, 0x88,
	0xde, 0x45, 0x33, 0x23, 0x97, 0x8c, 0x98, 0x8c, 0xd3, 0xb1, 0x43, 0x5e, 0xa7, 0x4f, 0xd7, 0x67,
	0xe8, 0x65, 0x65, 0xcf, 0xb1, 0x73, 0xec, 0x99, 0xe4, 0xd2, 0xdf, 0xb1, 0x7f, 0xe7, 0x64, 0xfc,
	0x1d, 0x9f, 0x90, 0x4e, 0x38, 0x4f, 0xfe, 0x5b, 0xb2, 0x28, 0x9c, 0x27, 0x97, 0xf3, 0x9c, 0x4b,
	0x4e, 0xb7, 0xc3, 0x79, 0x32, 0xd4, 0x72, 0xcc, 0x67, 0x33, 0x9e, 0x15, 0xf2, 0xf0, 0x58, 0x29,
	0x69, 0x22, 0xe4, 0x64, 0x9e, 0xf3, 0x28, 0x65, 0x33, 0x01, 0x81, 0xa1, 0x0d, 0x88, 0x45, 0x34,
	0x4b, 0x84, 0x48, 0x78, 0x26, 0x4a, 0x87, 0x62, 0x9e, 0x49, 0x26, 0xa4, 0x09, 0xf4, 0x0b, 0xbe,
	0xd6, 0x26, 0x22, 0x7c, 0x61, 0xa0, 0xb7, 0xf5, 0x01, 0xfe, 0x94, 0x98, 0xb4, 0x54, 0x09, 0x39,
	0x7b, 0x4a, 0x84, 0x64, 0x39, 0x3e, 0x2c, 0xa6, 0x7c, 0x69, 0x4a, 0xa9, 0x84, 0x4e, 0xf9, 0x12,
	0x74, 0xfd, 0x63, 0x74, 0x71, 0x12, 0xa7, 0x09, 0x23, 0xbe, 0x90, 0x78, 0x4b, 0xca, 0x9f, 0x56,
	0xca, 0x05, 0x86, 0x55, 0xfd, 0x6e, 0x27, 0x5b, 0xb8, 0x90, 0x53, 0xd0, 0xc7, 0xa5, 0x83, 0xe5,
	0xef, 0x32, 0xc4, 0x7b, 0xf2, 0x30, 0x7b, 0x56, 0xfb, 0x8a, 0xd8, 0xf8, 0x57, 0x8d, 0x34, 0x1f,
	0x59, 0xf4, 0x89, 0xc9, 0x80, 0x7d, 0x5f, 0x30, 0x21, 0xe9, 0x2d, 0x39, 0x72, 0x0a, 0x98, 0xe4,
	0x45, 0x60, 0xb0, 0x35, 0xda, 0xfa, 0xb7, 0xf1, 0xff, 0xe0, 0x52, 0x5d, 0xde, 0x6d, 0x22, 0xe4,
	0x1d, 0x6c, 0x80, 0x83, 0x41, 0x2f, 0x2d, 0x8b, 0xf4, 0x81, 0x0c, 0xfc, 0xaa, 0x2c, 0xf0, 0x0f,
	0x0d, 0x3c, 0xb5, 0xc0, 0xfb, 0xd5, 0x1e, 0xc3, 0xec, 0xa7, 0x95, 0xba, 0x2d, 0xd2, 0x5c, 0xb4,
	0x65, 0x6e, 0x7b, 0x45, 0x5e, 0xc3, 0x06, 0xa7, 0x48, 0x4f, 0xa4, 0x37, 0xe4, 0x10, 0x5f, 0xb0,
	0x85, 0xed, 0x68, 0xd8, 0xb1, 0x86, 0xdd, 0x4f, 0xf9, 0x12, 0x7e, 0x9c, 0x61, 0x51, 0x51, 0xd2,
	0xe8, 0x6b, 0xd2, 0xd4, 0x37, 0x6d, 0x19, 0x35, 0xcd, 0xe8, 0x6a, 0xc6, 0x95, 0x8a, 0x98, 0xd3,
	0x07, 0x21, 0x5a, 0xa9, 0x12, 0xb0, 0x97, 0xec, 0xf1, 0x5d, 0x54, 0x02, 0x94, 0xad, 0x2a, 0xb1,
	0x25, 0xc4, 0x25, 0x8d, 0x46, 0xe4, 0xac, 0xd2, 0x49, 0x96, 0xb9, 0xa7, 0x99, 0x17, 0x98, 0x59,
	0x75, 0x9f, 0xc3, 0x78, 0x6d, 0x8c, 0x3e, 0x93, 0xd1, 0x3a, 0xd3, 0xd9, 0x34, 0xfb, 0x3a, 0xcd,
	0xd8, 0x4f, 0x53, 0x71, 0xcb, 0x67, 0xf1, 0xa6, 0xb0, 0xf2, 0x90, 0xef, 0x5e, 0x9b, 0xa4, 0x8e,
	0x3c, 0x04, 0x49, 0x02, 0xd8, 0x63, 0x3d, 0x14, 0x57, 0xea, 0xe3, 0x1f, 0x3b, 0xa4, 0xf5, 0xc8,
	0xa2, 0x3b, 0x6e, 0x25, 0x7a, 0x46, 0x48, 0x2c, 0xf2, 0x6f, 0x13, 0xc9, 0x9f, 0x59, 0xa6, 0x0d,
	0x5f, 0x0f, 0xea, 0x4a, 0xf9, 0xa2, 0x04, 0x3a, 0x20, 0x7b, 0x71, 0x38, 0x97, 0xf1, 0x34, 0xd4,
	0xde, 0xad, 0x07, 0x66, 0x49, 0xaf, 0x09, 0xd5, 0xef, 0xc8, 0x24, 0xc9, 0x12, 0xe9, 0x99, 0xf1,
	0xa8, 0x30, 0xa3, 0x0a, 0xdf, 0x64, 0x89, 0x2d, 0xab, 0x93, 0x7a, 0xca, 0x0a, 0xa2, 0xfa, 0xdb,
	0x33, 0x21, 0x82, 0x5c, 0x2d, 0xe4, 0xd4, 0x85, 0x20, 0x85, 0xbe, 0x23, 0x1d, 0xf3, 0x80, 0x79,
	0x1e, 0x3c, 0xd4, 0x88, 0x00, 0x82, 0x86, 0xd0, 0xce, 0x5d, 0x81, 0xbe, 0x21, 0xad, 0xe2, 0xf5,
	0xf2, 0x3c, 0x48, 0x8b, 0x36, 0xd0, 0x21, 0x73, 0xb8, 0x29, 0xf0, 0x52, 0x1d, 0x2d, 0x5e, 0x35,
	0xcf, 0x6a, 0xd4, 0x14, 0x8f, 0xec, 0xdf, 0x4c, 0xf1, 0xd2, 0xf1, 0x7f, 0xf8, 0xc2, 0x3c, 0x13,
	0xb9, 0xfe, 0x0f, 0x5f, 0x58, 0xc9, 0xff, 0x2b, 0x0d, 0xa3, 0x9c, 0x0f, 0x59, 0x2f, 0xa3, 0xf0,
	0xa7, 0x34, 0x28, 0xa4, 0x8d, 0x7f, 0x12, 0xd2, 0x78, 0x64, 0x51, 0xc0, 0xc4, 0x9c, 0x67, 0x82,
	0xd1, 0x7f, 0x48, 0x4b, 0x30, 0x39, 0x29, 0x79, 0xe4, 0x40, 0x30, 0x79, 0x6d, 0x6d, 0x72, 0x41,
	0x1a, 0xe0, 0x8b, 0xc9, 0x22, 0x4f, 0xc1, 0x2a, 0x04, 0xa4, 0x87, 0x3c, 0xa5, 0x9f, 0x49, 0xdf,
	0xef, 0xcc, 0x22, 0x01, 0x38, 0xe6, 0xa4, 0xe2, 0x8d, 0x2d, 0x36, 0x04, 0x87, 0x69, 0x85, 0x4a,
	0xbf, 0x92, 0x93, 0x8a, 0x36, 0x04, 0x66, 0x61, 0xa0, 0x3f, 0xab, 0x9f, 0x59, 0xc0, 0x1e, 0xa7,
	0xd5, 0x01, 0x5b, 0x2a, 0x7a, 0x68, 0x01, 0x5b, 0xf3, 0x4a, 0x5d, 0x3d, 0xaa, 0xb8, 0x54, 0x5f,
	0xa5, 0x1f, 0x49, 0xcf, 0xe9, 0x14, 0xa0, 0x15, 0x1e, 0xeb, 0xfb, 0xad, 0x02, 0xa8, 0x6e, 0xea,
	0x4b, 0x2b, 0x0e, 0xdc, 0x31, 0x70, 0xf6, 0x7c, 0x4e, 0x71, 0x9d, 0x0e, 0x07, 0x4b, 0xf4, 0x3d,
	0xe9, 0xa2, 0x7e, 0x01, 0xca, 0x3e, 0xea, 0xb9, 0x55, 0xc3, 0x00, 0xa4, 0x93, 0x7b, 0x8a, 0x9a,
	0x46, 0xde, 0xfc, 0x00, 0x4e, 0x1d, 0x4d, 0x23, 0x67, 0x80, 0x00, 0xaa, 0x27, 0xca, 0x22, 0x7d,
	0x4b, 0xda, 0xb6, 0x01, 0x81, 0x43, 0x34, 0xa7, 0xe7, 0x74, 0x20, 0x20, 0x5a, 0xc2, 0x59, 0xab,
	0x1e, 0x34, 0x03, 0x08, 0x0e, 0x37, 0x50, 0x0f, 0xc2, 0x04, 0x82, 0xb3, 0xcd, 0x10, 0x2f, 0x55,
	0x62, 0xdb, 0xbe, 0x70, 0xf6, 0x00, 0x25, 0x36, 0xfd, 0x6b, 0x12, 0xa7, 0xce, 0x5a, 0x7d, 0x04,
	0x6f, 0x82, 0x01, 0xa3, 0x89, 0x3e, 0x82, 0x33, 0xc2, 0xcc, 0x47, 0x88, 0xcb, 0xa2, 0x43, 0x2b,
	0xde, 0x03, 0xa0, 0xb5, 0x2a, 0x68, 0xba, 0xf9, 0x7d, 0x1a, 0x12, 0x29, 0x23, 0xe7, 0xeb, 0x46,
	0x22, 0x60, 0xdb, 0x1a, 0x3b, 0x5a, 0x3f, 0x13, 0x01, 0x7f, 0x1a, 0xaf, 0x0f, 0xe2, 0xa2, 0x5d,
	0x57, 0x76, 0xca, 0x45, 0x3b, 0xbe, 0xec, 0xc5, 0x65, 0x91, 0x66, 0xe4, 0xaf, 0x0d, 0x33, 0x16,
	0xc8, 0x5d, 0x4d, 0xfe, 0x7b, 0xe3, 0x90, 0x85, 0x24, 0xe7, 0xf1, 0xc6, 0xb8, 0x7a, 0x44, 0x2a,
	0xc6, 0x2c, 0xe4, 0xa1, 0xe8, 0x11, 0x29, 0xcd, 0x59, 0xf3, 0x88, 0xc4, 0xd5, 0x01, 0x3a, 0x22,
	0x35, 0x96, 0xe7, 0x3c, 0x1f, 0xf4, 0x34, 0x85, 0x68, 0xca, 0x07, 0xa5, 0x04, 0x45, 0x20, 0xda,
	0xd5, 0xff, 0x46, 0x5f, 0xfd, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xe8, 0xcf, 0x91, 0xfc, 0x21, 0x0c,
	0x00, 0x00,
}
