// Code generated by protoc-gen-go.
// source: api/webapi.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type WebGetRequest struct {
	ListProblemsRequest           *ListProblemsRequest           `protobuf:"bytes,1,opt,name=list_problems_request,json=listProblemsRequest" json:"list_problems_request,omitempty"`
	ListSubmissionsRequest        *ListSubmissionsRequest        `protobuf:"bytes,2,opt,name=list_submissions_request,json=listSubmissionsRequest" json:"list_submissions_request,omitempty"`
	ListContestsRequest           *ListContestsRequest           `protobuf:"bytes,3,opt,name=list_contests_request,json=listContestsRequest" json:"list_contests_request,omitempty"`
	ShowProblemRequest            *ShowProblemRequest            `protobuf:"bytes,4,opt,name=show_problem_request,json=showProblemRequest" json:"show_problem_request,omitempty"`
	AboutRequest                  *AboutRequest                  `protobuf:"bytes,5,opt,name=about_request,json=aboutRequest" json:"about_request,omitempty"`
	ContestShowRequest            *ContestShowRequest            `protobuf:"bytes,6,opt,name=contest_show_request,json=contestShowRequest" json:"contest_show_request,omitempty"`
	ContestListProblemsRequest    *ContestListProblemsRequest    `protobuf:"bytes,7,opt,name=contest_list_problems_request,json=contestListProblemsRequest" json:"contest_list_problems_request,omitempty"`
	ContestListSubmissionsRequest *ContestListSubmissionsRequest `protobuf:"bytes,8,opt,name=contest_list_submissions_request,json=contestListSubmissionsRequest" json:"contest_list_submissions_request,omitempty"`
	ContestRanklistRequest        *ContestRanklistRequest        `protobuf:"bytes,9,opt,name=contest_ranklist_request,json=contestRanklistRequest" json:"contest_ranklist_request,omitempty"`
}

func (m *WebGetRequest) Reset()                    { *m = WebGetRequest{} }
func (m *WebGetRequest) String() string            { return proto.CompactTextString(m) }
func (*WebGetRequest) ProtoMessage()               {}
func (*WebGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{0} }

func (m *WebGetRequest) GetListProblemsRequest() *ListProblemsRequest {
	if m != nil {
		return m.ListProblemsRequest
	}
	return nil
}

func (m *WebGetRequest) GetListSubmissionsRequest() *ListSubmissionsRequest {
	if m != nil {
		return m.ListSubmissionsRequest
	}
	return nil
}

func (m *WebGetRequest) GetListContestsRequest() *ListContestsRequest {
	if m != nil {
		return m.ListContestsRequest
	}
	return nil
}

func (m *WebGetRequest) GetShowProblemRequest() *ShowProblemRequest {
	if m != nil {
		return m.ShowProblemRequest
	}
	return nil
}

func (m *WebGetRequest) GetAboutRequest() *AboutRequest {
	if m != nil {
		return m.AboutRequest
	}
	return nil
}

func (m *WebGetRequest) GetContestShowRequest() *ContestShowRequest {
	if m != nil {
		return m.ContestShowRequest
	}
	return nil
}

func (m *WebGetRequest) GetContestListProblemsRequest() *ContestListProblemsRequest {
	if m != nil {
		return m.ContestListProblemsRequest
	}
	return nil
}

func (m *WebGetRequest) GetContestListSubmissionsRequest() *ContestListSubmissionsRequest {
	if m != nil {
		return m.ContestListSubmissionsRequest
	}
	return nil
}

func (m *WebGetRequest) GetContestRanklistRequest() *ContestRanklistRequest {
	if m != nil {
		return m.ContestRanklistRequest
	}
	return nil
}

// WebRequest are all POST requests
type WebPostRequest struct {
	CsrfToken          string              `protobuf:"bytes,1,opt,name=csrf_token,json=csrfToken" json:"csrf_token,omitempty"`
	Captcha            string              `protobuf:"bytes,2,opt,name=captcha" json:"captcha,omitempty"`
	LoginInitRequest   *LoginInitRequest   `protobuf:"bytes,3,opt,name=login_init_request,json=loginInitRequest" json:"login_init_request,omitempty"`
	LoginAuthRequest   *LoginAuthRequest   `protobuf:"bytes,4,opt,name=login_auth_request,json=loginAuthRequest" json:"login_auth_request,omitempty"`
	RegisterRequest    *RegisterRequest    `protobuf:"bytes,5,opt,name=register_request,json=registerRequest" json:"register_request,omitempty"`
	SubmitRequest      *SubmitRequest      `protobuf:"bytes,6,opt,name=submit_request,json=submitRequest" json:"submit_request,omitempty"`
	LogoutRequest      *LogoutRequest      `protobuf:"bytes,7,opt,name=logout_request,json=logoutRequest" json:"logout_request,omitempty"`
	ContestSaveRequest *ContestSaveRequest `protobuf:"bytes,8,opt,name=contest_save_request,json=contestSaveRequest" json:"contest_save_request,omitempty"`
	ContestAuthRequest *ContestAuthRequest `protobuf:"bytes,9,opt,name=contest_auth_request,json=contestAuthRequest" json:"contest_auth_request,omitempty"`
	ReJudgeRequest     *ReJudgeRequest     `protobuf:"bytes,10,opt,name=re_judge_request,json=reJudgeRequest" json:"re_judge_request,omitempty"`
}

func (m *WebPostRequest) Reset()                    { *m = WebPostRequest{} }
func (m *WebPostRequest) String() string            { return proto.CompactTextString(m) }
func (*WebPostRequest) ProtoMessage()               {}
func (*WebPostRequest) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{1} }

func (m *WebPostRequest) GetCsrfToken() string {
	if m != nil {
		return m.CsrfToken
	}
	return ""
}

func (m *WebPostRequest) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

func (m *WebPostRequest) GetLoginInitRequest() *LoginInitRequest {
	if m != nil {
		return m.LoginInitRequest
	}
	return nil
}

func (m *WebPostRequest) GetLoginAuthRequest() *LoginAuthRequest {
	if m != nil {
		return m.LoginAuthRequest
	}
	return nil
}

func (m *WebPostRequest) GetRegisterRequest() *RegisterRequest {
	if m != nil {
		return m.RegisterRequest
	}
	return nil
}

func (m *WebPostRequest) GetSubmitRequest() *SubmitRequest {
	if m != nil {
		return m.SubmitRequest
	}
	return nil
}

func (m *WebPostRequest) GetLogoutRequest() *LogoutRequest {
	if m != nil {
		return m.LogoutRequest
	}
	return nil
}

func (m *WebPostRequest) GetContestSaveRequest() *ContestSaveRequest {
	if m != nil {
		return m.ContestSaveRequest
	}
	return nil
}

func (m *WebPostRequest) GetContestAuthRequest() *ContestAuthRequest {
	if m != nil {
		return m.ContestAuthRequest
	}
	return nil
}

func (m *WebPostRequest) GetReJudgeRequest() *ReJudgeRequest {
	if m != nil {
		return m.ReJudgeRequest
	}
	return nil
}

type WebResponse struct {
	SetCsrfToken                   string                          `protobuf:"bytes,1,opt,name=set_csrf_token,json=setCsrfToken" json:"set_csrf_token,omitempty"`
	CaptchaUrl                     string                          `protobuf:"bytes,2,opt,name=captcha_url,json=captchaUrl" json:"captcha_url,omitempty"`
	ListProblemsResponse           *ListProblemsResponse           `protobuf:"bytes,3,opt,name=list_problems_response,json=listProblemsResponse" json:"list_problems_response,omitempty"`
	ListSubmissionsResponse        *ListSubmissionsResponse        `protobuf:"bytes,4,opt,name=list_submissions_response,json=listSubmissionsResponse" json:"list_submissions_response,omitempty"`
	ListContestsResponse           *ListContestsResponse           `protobuf:"bytes,5,opt,name=list_contests_response,json=listContestsResponse" json:"list_contests_response,omitempty"`
	LoginInitResponse              *LoginInitResponse              `protobuf:"bytes,6,opt,name=login_init_response,json=loginInitResponse" json:"login_init_response,omitempty"`
	LoginAuthResponse              *LoginAuthResponse              `protobuf:"bytes,7,opt,name=login_auth_response,json=loginAuthResponse" json:"login_auth_response,omitempty"`
	RegisterResponse               *RegisterResponse               `protobuf:"bytes,8,opt,name=register_response,json=registerResponse" json:"register_response,omitempty"`
	ShowProblemResponse            *ShowProblemResponse            `protobuf:"bytes,9,opt,name=show_problem_response,json=showProblemResponse" json:"show_problem_response,omitempty"`
	SubmitResponse                 *SubmitResponse                 `protobuf:"bytes,10,opt,name=submit_response,json=submitResponse" json:"submit_response,omitempty"`
	AboutResponse                  *AboutResponse                  `protobuf:"bytes,11,opt,name=about_response,json=aboutResponse" json:"about_response,omitempty"`
	LogoutResponse                 *LogoutResponse                 `protobuf:"bytes,12,opt,name=logout_response,json=logoutResponse" json:"logout_response,omitempty"`
	ContestShowResponse            *ContestShowResponse            `protobuf:"bytes,13,opt,name=contest_show_response,json=contestShowResponse" json:"contest_show_response,omitempty"`
	ContestSaveResponse            *ContestSaveResponse            `protobuf:"bytes,14,opt,name=contest_save_response,json=contestSaveResponse" json:"contest_save_response,omitempty"`
	ContestListProblemsResponse    *ContestListProblemsResponse    `protobuf:"bytes,15,opt,name=contest_list_problems_response,json=contestListProblemsResponse" json:"contest_list_problems_response,omitempty"`
	ContestAuthResponse            *ContestAuthResponse            `protobuf:"bytes,16,opt,name=contest_auth_response,json=contestAuthResponse" json:"contest_auth_response,omitempty"`
	ContestListSubmissionsResponse *ContestListSubmissionsResponse `protobuf:"bytes,17,opt,name=contest_list_submissions_response,json=contestListSubmissionsResponse" json:"contest_list_submissions_response,omitempty"`
	ContestRanklistResponse        *ContestRanklistResponse        `protobuf:"bytes,18,opt,name=contest_ranklist_response,json=contestRanklistResponse" json:"contest_ranklist_response,omitempty"`
	ReJudgeResponse                *ReJudgeResponse                `protobuf:"bytes,19,opt,name=re_judge_response,json=reJudgeResponse" json:"re_judge_response,omitempty"`
	Error                          *Error                          `protobuf:"bytes,20,opt,name=error" json:"error,omitempty"`
}

func (m *WebResponse) Reset()                    { *m = WebResponse{} }
func (m *WebResponse) String() string            { return proto.CompactTextString(m) }
func (*WebResponse) ProtoMessage()               {}
func (*WebResponse) Descriptor() ([]byte, []int) { return fileDescriptor21, []int{2} }

func (m *WebResponse) GetSetCsrfToken() string {
	if m != nil {
		return m.SetCsrfToken
	}
	return ""
}

func (m *WebResponse) GetCaptchaUrl() string {
	if m != nil {
		return m.CaptchaUrl
	}
	return ""
}

func (m *WebResponse) GetListProblemsResponse() *ListProblemsResponse {
	if m != nil {
		return m.ListProblemsResponse
	}
	return nil
}

func (m *WebResponse) GetListSubmissionsResponse() *ListSubmissionsResponse {
	if m != nil {
		return m.ListSubmissionsResponse
	}
	return nil
}

func (m *WebResponse) GetListContestsResponse() *ListContestsResponse {
	if m != nil {
		return m.ListContestsResponse
	}
	return nil
}

func (m *WebResponse) GetLoginInitResponse() *LoginInitResponse {
	if m != nil {
		return m.LoginInitResponse
	}
	return nil
}

func (m *WebResponse) GetLoginAuthResponse() *LoginAuthResponse {
	if m != nil {
		return m.LoginAuthResponse
	}
	return nil
}

func (m *WebResponse) GetRegisterResponse() *RegisterResponse {
	if m != nil {
		return m.RegisterResponse
	}
	return nil
}

func (m *WebResponse) GetShowProblemResponse() *ShowProblemResponse {
	if m != nil {
		return m.ShowProblemResponse
	}
	return nil
}

func (m *WebResponse) GetSubmitResponse() *SubmitResponse {
	if m != nil {
		return m.SubmitResponse
	}
	return nil
}

func (m *WebResponse) GetAboutResponse() *AboutResponse {
	if m != nil {
		return m.AboutResponse
	}
	return nil
}

func (m *WebResponse) GetLogoutResponse() *LogoutResponse {
	if m != nil {
		return m.LogoutResponse
	}
	return nil
}

func (m *WebResponse) GetContestShowResponse() *ContestShowResponse {
	if m != nil {
		return m.ContestShowResponse
	}
	return nil
}

func (m *WebResponse) GetContestSaveResponse() *ContestSaveResponse {
	if m != nil {
		return m.ContestSaveResponse
	}
	return nil
}

func (m *WebResponse) GetContestListProblemsResponse() *ContestListProblemsResponse {
	if m != nil {
		return m.ContestListProblemsResponse
	}
	return nil
}

func (m *WebResponse) GetContestAuthResponse() *ContestAuthResponse {
	if m != nil {
		return m.ContestAuthResponse
	}
	return nil
}

func (m *WebResponse) GetContestListSubmissionsResponse() *ContestListSubmissionsResponse {
	if m != nil {
		return m.ContestListSubmissionsResponse
	}
	return nil
}

func (m *WebResponse) GetContestRanklistResponse() *ContestRanklistResponse {
	if m != nil {
		return m.ContestRanklistResponse
	}
	return nil
}

func (m *WebResponse) GetReJudgeResponse() *ReJudgeResponse {
	if m != nil {
		return m.ReJudgeResponse
	}
	return nil
}

func (m *WebResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*WebGetRequest)(nil), "api.WebGetRequest")
	proto.RegisterType((*WebPostRequest)(nil), "api.WebPostRequest")
	proto.RegisterType((*WebResponse)(nil), "api.WebResponse")
}

func init() { proto.RegisterFile("api/webapi.proto", fileDescriptor21) }

var fileDescriptor21 = []byte{
	// 947 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x96, 0xdf, 0x6e, 0x23, 0x35,
	0x14, 0xc6, 0xb5, 0xec, 0x66, 0xbb, 0x71, 0x9a, 0x7f, 0x4e, 0x36, 0xcd, 0x66, 0xe9, 0x36, 0x04,
	0x2e, 0xb8, 0x5a, 0x24, 0x90, 0x90, 0x90, 0x40, 0x50, 0x2a, 0x40, 0x45, 0x95, 0xa8, 0xa6, 0x54,
	0xe5, 0x6e, 0x34, 0x33, 0x98, 0x64, 0xe8, 0x64, 0x1c, 0x6c, 0xa7, 0x79, 0x25, 0xde, 0x8a, 0xd7,
	0xe0, 0x72, 0x65, 0xcf, 0xb1, 0x73, 0xec, 0x99, 0xe4, 0xd2, 0xdf, 0xb1, 0x7f, 0x3e, 0xf1, 0x7c,
	0xe7, 0x9c, 0x90, 0x41, 0xb2, 0xc9, 0xbf, 0xd8, 0xb1, 0x34, 0xd9, 0xe4, 0xef, 0x37, 0x82, 0x2b,
	0x4e, 0x9f, 0x27, 0x9b, 0x7c, 0x66, 0xe4, 0x8c, 0xaf, 0xd7, 0xbc, 0xac, 0xe4, 0xd9, 0x99, 0x56,
	0x8a, 0x5c, 0xaa, 0x78, 0x23, 0x78, 0x5a, 0xb0, 0xb5, 0x84, 0xc0, 0xcc, 0x05, 0xe4, 0x36, 0x5d,
	0xe7, 0x52, 0xe6, 0xbc, 0x94, 0xb5, 0x43, 0x19, 0x2f, 0x15, 0x93, 0xca, 0x06, 0x26, 0x15, 0xdf,
	0x68, 0xb1, 0x4c, 0x9e, 0x18, 0xe8, 0x7d, 0x73, 0x80, 0x2f, 0x73, 0x7b, 0x2d, 0xd5, 0x82, 0x60,
	0xcb, 0x5c, 0x2a, 0x26, 0xf0, 0x61, 0xb9, 0xe2, 0x3b, 0x9b, 0x4a, 0x23, 0x74, 0xc5, 0x77, 0xa0,
	0x9b, 0x1f, 0x63, 0x92, 0x53, 0xf8, 0x9a, 0x24, 0xe5, 0x5b, 0x85, 0xb7, 0x14, 0x7c, 0xb9, 0x57,
	0x2e, 0x30, 0xac, 0xe9, 0x77, 0x7b, 0xb7, 0x25, 0x5b, 0xb5, 0x02, 0x7d, 0x51, 0x3b, 0x58, 0x7f,
	0x97, 0x19, 0xde, 0x23, 0x92, 0xf2, 0x51, 0xef, 0x83, 0xd8, 0xb0, 0xfa, 0xc5, 0x7f, 0x6f, 0xff,
	0x5c, 0xc2, 0xab, 0x2c, 0xfe, 0x6f, 0x91, 0xee, 0x03, 0x4b, 0x7f, 0x61, 0x2a, 0x62, 0xff, 0x6c,
	0x99, 0x54, 0xf4, 0x86, 0xbc, 0xf6, 0x72, 0x8a, 0x45, 0x15, 0x98, 0x3e, 0x9b, 0x3f, 0xfb, 0xbc,
	0xf3, 0xe5, 0xf4, 0xbd, 0xfe, 0x9e, 0x37, 0xb9, 0x54, 0xb7, 0xb0, 0x01, 0x0e, 0x46, 0xa3, 0xa2,
	0x2e, 0xd2, 0x7b, 0x32, 0x0d, 0x13, 0x75, 0xc0, 0x8f, 0x0c, 0xf0, 0xad, 0x03, 0xde, 0xed, 0xf7,
	0x58, 0xe6, 0xa4, 0x68, 0xd4, 0x5d, 0x92, 0xf6, 0xdb, 0x3b, 0xe6, 0xf3, 0x20, 0xc9, 0x2b, 0xd8,
	0xe0, 0x25, 0x19, 0x88, 0xf4, 0x9a, 0x8c, 0xf1, 0x37, 0x77, 0xb0, 0x17, 0x06, 0x76, 0x66, 0x60,
	0x77, 0x2b, 0xbe, 0x83, 0x1f, 0x67, 0x59, 0x54, 0xd6, 0x34, 0xfa, 0x35, 0xe9, 0x9a, 0x8f, 0xef,
	0x18, 0x2d, 0xc3, 0x18, 0x1a, 0xc6, 0xa5, 0x8e, 0xd8, 0xd3, 0xa7, 0x09, 0x5a, 0xe9, 0x14, 0xb0,
	0xbd, 0xdc, 0xf1, 0x97, 0x28, 0x05, 0x48, 0x5b, 0x67, 0xe2, 0x52, 0xc8, 0x6a, 0x1a, 0x4d, 0xc9,
	0x79, 0xa3, 0xb9, 0x1c, 0xf3, 0xc4, 0x30, 0x2f, 0x30, 0xb3, 0xe9, 0x7b, 0xce, 0xb2, 0x83, 0x31,
	0xfa, 0x48, 0xe6, 0x87, 0x7c, 0xe8, 0xae, 0x79, 0x65, 0xae, 0x59, 0x84, 0xd7, 0x34, 0x7c, 0xe5,
	0xf3, 0xec, 0x58, 0x58, 0x7b, 0x28, 0x34, 0xb4, 0xbb, 0xa4, 0x8d, 0x3c, 0x04, 0x97, 0x44, 0xb0,
	0xc7, 0x79, 0x28, 0x6b, 0xd4, 0x17, 0xff, 0xbd, 0x20, 0xbd, 0x07, 0x96, 0xde, 0x72, 0x27, 0xd1,
	0x73, 0x42, 0x32, 0x29, 0xfe, 0x8a, 0x15, 0x7f, 0x64, 0xa5, 0x31, 0x7c, 0x3b, 0x6a, 0x6b, 0xe5,
	0x77, 0x2d, 0xd0, 0x29, 0x39, 0xc9, 0x92, 0x8d, 0xca, 0x56, 0x89, 0xf1, 0x6e, 0x3b, 0xb2, 0x4b,
	0x7a, 0x45, 0xa8, 0x69, 0x2d, 0x71, 0x5e, 0xe6, 0x2a, 0x30, 0xe3, 0xeb, 0xca, 0x8c, 0x3a, 0x7c,
	0x5d, 0xe6, 0x2e, 0xad, 0x41, 0x11, 0x28, 0x7b, 0x88, 0x2e, 0xf9, 0xc0, 0x84, 0x08, 0x72, 0xb9,
	0x55, 0x2b, 0x1f, 0x82, 0x14, 0xfa, 0x3d, 0x19, 0xd8, 0x9e, 0x16, 0x78, 0x70, 0x6c, 0x10, 0x11,
	0x04, 0x2d, 0xa1, 0x2f, 0x7c, 0x81, 0x7e, 0x43, 0x7a, 0x55, 0x43, 0x0b, 0x3c, 0x48, 0xab, 0x32,
	0x30, 0x21, 0x7b, 0xb8, 0x2b, 0xf1, 0x52, 0x1f, 0xad, 0x1a, 0x5d, 0x60, 0x35, 0x6a, 0x93, 0x47,
	0xf6, 0xef, 0x16, 0x78, 0xe9, 0xf9, 0x3f, 0x79, 0x62, 0x81, 0x89, 0x7c, 0xff, 0x27, 0x4f, 0xac,
	0xe6, 0xff, 0xbd, 0x86, 0x51, 0xde, 0x43, 0xb6, 0xeb, 0x28, 0xfc, 0x94, 0x16, 0x85, 0x1f, 0xf3,
	0x3b, 0xfd, 0x98, 0xb1, 0xe9, 0x97, 0x0e, 0x43, 0x0c, 0x66, 0x04, 0x8f, 0xf9, 0xab, 0x8e, 0x59,
	0x44, 0x4f, 0x78, 0xeb, 0xc5, 0xbf, 0x1d, 0xd2, 0x79, 0x60, 0x69, 0xc4, 0xe4, 0x86, 0x97, 0x92,
	0xd1, 0xcf, 0x48, 0x4f, 0x32, 0x15, 0xd7, 0x2c, 0x76, 0x2a, 0x99, 0xba, 0x72, 0x2e, 0xbb, 0x20,
	0x1d, 0xb0, 0x55, 0xbc, 0x15, 0x05, 0x38, 0x8d, 0x80, 0x74, 0x2f, 0x0a, 0xfa, 0x1b, 0x99, 0x84,
	0x85, 0x5d, 0x5d, 0x00, 0x86, 0x7b, 0xd3, 0xd0, 0xa2, 0xab, 0x0d, 0xd1, 0xb8, 0x68, 0x50, 0xe9,
	0x1f, 0xe4, 0x4d, 0x43, 0x15, 0x03, 0xb3, 0xf2, 0xdf, 0xc7, 0xcd, 0x5d, 0x1a, 0xb0, 0x67, 0x45,
	0x73, 0xc0, 0xa5, 0x8a, 0xfa, 0x34, 0x60, 0x5b, 0x41, 0xaa, 0xfb, 0x9e, 0x8c, 0x53, 0x0d, 0x55,
	0xfa, 0x33, 0x19, 0x79, 0x85, 0x06, 0xb4, 0xca, 0xa2, 0x93, 0xb0, 0xd2, 0x00, 0x35, 0x2c, 0x42,
	0x69, 0xcf, 0x01, 0x8b, 0x00, 0xe7, 0x24, 0xe4, 0x54, 0x6e, 0xf0, 0x38, 0x58, 0xa2, 0x3f, 0x92,
	0x21, 0x2a, 0x37, 0xa0, 0xbc, 0x42, 0x25, 0xbb, 0xaf, 0x37, 0x80, 0x0c, 0x44, 0xa0, 0xe8, 0x61,
	0x16, 0x8c, 0x1f, 0xe0, 0xb4, 0xd1, 0x30, 0xf3, 0xe6, 0x0f, 0xa0, 0x46, 0xb2, 0x2e, 0xd2, 0x6f,
	0x49, 0xdf, 0xd5, 0x2f, 0x70, 0xb0, 0x65, 0x6d, 0x01, 0x03, 0xa2, 0x27, 0xbd, 0xb5, 0x2e, 0x61,
	0x3b, 0xbf, 0xe0, 0x70, 0x07, 0x95, 0x30, 0x0c, 0x30, 0x38, 0xdb, 0x4d, 0xf0, 0x52, 0x5f, 0xec,
	0xaa, 0x1f, 0xce, 0x9e, 0xa2, 0x8b, 0x6d, 0xf9, 0xdb, 0x8b, 0x0b, 0x6f, 0xad, 0x1f, 0x21, 0x18,
	0x80, 0xc0, 0xe8, 0xa2, 0x47, 0xf0, 0x26, 0xa0, 0x7d, 0x84, 0xac, 0x2e, 0x7a, 0xb4, 0xaa, 0x9d,
	0x00, 0xad, 0xd7, 0x40, 0x33, 0xbd, 0x23, 0xa4, 0x21, 0x91, 0x32, 0xf2, 0xee, 0xd0, 0x44, 0x05,
	0x6c, 0xdf, 0x60, 0xe7, 0x87, 0x47, 0x2a, 0xe0, 0xdf, 0x66, 0x87, 0x83, 0x38, 0x69, 0xdf, 0x95,
	0x83, 0x7a, 0xd2, 0x9e, 0x2f, 0x47, 0x59, 0x5d, 0xa4, 0x25, 0xf9, 0xe4, 0xc8, 0x88, 0x06, 0xf2,
	0xd0, 0x90, 0x3f, 0x3d, 0x3a, 0xa3, 0xe1, 0x92, 0x77, 0xd9, 0xd1, 0xb8, 0x6e, 0x22, 0x0d, 0x53,
	0x1a, 0xee, 0xa1, 0xa8, 0x89, 0xd4, 0xc6, 0xb4, 0x6d, 0x22, 0x59, 0x73, 0x80, 0xfe, 0xa0, 0x6b,
	0xcc, 0x75, 0x61, 0x20, 0x8e, 0xbc, 0x99, 0x06, 0x6d, 0x17, 0x48, 0x7d, 0xe1, 0x0b, 0x74, 0x4e,
	0x5a, 0x4c, 0x08, 0x2e, 0xa6, 0x63, 0x73, 0x8a, 0x98, 0x53, 0x3f, 0x69, 0x25, 0xaa, 0x02, 0xe9,
	0x4b, 0xf3, 0x77, 0xf8, 0xab, 0x0f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xf1, 0x4d, 0xf4, 0xbf, 0xb5,
	0x0c, 0x00, 0x00,
}
