// Code generated by protoc-gen-go.
// source: api/login.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LoginInitRequest struct {
	Msg     string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *LoginInitRequest) Reset()                    { *m = LoginInitRequest{} }
func (m *LoginInitRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginInitRequest) ProtoMessage()               {}
func (*LoginInitRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *LoginInitRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoginInitRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LoginInitResponse struct {
	Salt      []byte `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	Version   string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	IsCaptcha bool   `protobuf:"varint,3,opt,name=is_captcha,json=isCaptcha" json:"is_captcha,omitempty"`
	Error     *Error `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *LoginInitResponse) Reset()                    { *m = LoginInitResponse{} }
func (m *LoginInitResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginInitResponse) ProtoMessage()               {}
func (*LoginInitResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *LoginInitResponse) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *LoginInitResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LoginInitResponse) GetIsCaptcha() bool {
	if m != nil {
		return m.IsCaptcha
	}
	return false
}

func (m *LoginInitResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type LoginAuthRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Passwd   string `protobuf:"bytes,2,opt,name=passwd" json:"passwd,omitempty"`
	Captcha  string `protobuf:"bytes,3,opt,name=captcha" json:"captcha,omitempty"`
}

func (m *LoginAuthRequest) Reset()                    { *m = LoginAuthRequest{} }
func (m *LoginAuthRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginAuthRequest) ProtoMessage()               {}
func (*LoginAuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *LoginAuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginAuthRequest) GetPasswd() string {
	if m != nil {
		return m.Passwd
	}
	return ""
}

func (m *LoginAuthRequest) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

type LoginAuthResponse struct {
	Msg       string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	Privilege string `protobuf:"bytes,2,opt,name=privilege" json:"privilege,omitempty"`
	Error     *Error `protobuf:"bytes,3,opt,name=error" json:"error,omitempty"`
}

func (m *LoginAuthResponse) Reset()                    { *m = LoginAuthResponse{} }
func (m *LoginAuthResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginAuthResponse) ProtoMessage()               {}
func (*LoginAuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *LoginAuthResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoginAuthResponse) GetPrivilege() string {
	if m != nil {
		return m.Privilege
	}
	return ""
}

func (m *LoginAuthResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginInitRequest)(nil), "api.LoginInitRequest")
	proto.RegisterType((*LoginInitResponse)(nil), "api.LoginInitResponse")
	proto.RegisterType((*LoginAuthRequest)(nil), "api.LoginAuthRequest")
	proto.RegisterType((*LoginAuthResponse)(nil), "api.LoginAuthResponse")
}

func init() { proto.RegisterFile("api/login.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xa9, 0x5d, 0xd7, 0xed, 0x28, 0x58, 0x73, 0x90, 0xb2, 0x28, 0x94, 0x9e, 0x7a, 0xaa,
	0xa0, 0x77, 0x41, 0xc4, 0x83, 0xe0, 0x29, 0x2f, 0xa0, 0xb1, 0x0e, 0xdd, 0x81, 0xb6, 0x89, 0x99,
	0x74, 0xbd, 0xfb, 0xe4, 0x92, 0x36, 0x75, 0x17, 0x96, 0xbd, 0xcd, 0xff, 0xb5, 0xfc, 0x99, 0x2f,
	0x81, 0x4b, 0x65, 0xe8, 0xae, 0xd5, 0x0d, 0xf5, 0x95, 0xb1, 0xda, 0x69, 0x11, 0x2b, 0x43, 0xeb,
	0xd4, 0xd3, 0x5a, 0x77, 0x9d, 0x0e, 0xb8, 0x78, 0x84, 0xf4, 0xcd, 0xff, 0xf5, 0xda, 0x93, 0x93,
	0xf8, 0x3d, 0x20, 0x3b, 0x91, 0x42, 0xdc, 0x71, 0x93, 0x45, 0x79, 0x54, 0x26, 0xd2, 0x8f, 0x22,
	0x83, 0xb3, 0x2d, 0x5a, 0x26, 0xdd, 0x67, 0x27, 0x23, 0x9d, 0x63, 0xf1, 0x1b, 0xc1, 0xd5, 0x5e,
	0x01, 0x1b, 0xdd, 0x33, 0x0a, 0x01, 0x0b, 0x56, 0xad, 0x1b, 0x2b, 0x2e, 0xe4, 0x38, 0x1f, 0xef,
	0x10, 0xb7, 0x00, 0xc4, 0xef, 0xb5, 0x32, 0xae, 0xde, 0xa8, 0x2c, 0xce, 0xa3, 0x72, 0x25, 0x13,
	0xe2, 0xe7, 0x09, 0x88, 0x1c, 0x4e, 0xd1, 0x5a, 0x6d, 0xb3, 0x45, 0x1e, 0x95, 0xe7, 0xf7, 0x50,
	0x29, 0x43, 0xd5, 0x8b, 0x27, 0x72, 0xfa, 0x50, 0x7c, 0x04, 0x89, 0xa7, 0xc1, 0x6d, 0x66, 0x89,
	0x35, 0xac, 0x06, 0x46, 0xdb, 0xab, 0x0e, 0x83, 0xc9, 0x7f, 0x16, 0xd7, 0xb0, 0x34, 0x8a, 0xf9,
	0xe7, 0x2b, 0x6c, 0x12, 0x92, 0x5f, 0x71, 0x7f, 0x8b, 0x44, 0xce, 0xb1, 0xc0, 0x60, 0x39, 0x9d,
	0x10, 0x2c, 0x0f, 0xef, 0xe9, 0x06, 0x12, 0x63, 0x69, 0x4b, 0x2d, 0x36, 0x18, 0xba, 0x77, 0x60,
	0x27, 0x12, 0x1f, 0x11, 0xf9, 0x5c, 0x8e, 0x8f, 0xf2, 0xf0, 0x17, 0x00, 0x00, 0xff, 0xff, 0xe3,
	0x70, 0x82, 0x9c, 0xbe, 0x01, 0x00, 0x00,
}
