// Code generated by protoc-gen-go.
// source: api/login.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LoginInitRequest struct {
	Msg     string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	Version string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
}

func (m *LoginInitRequest) Reset()                    { *m = LoginInitRequest{} }
func (m *LoginInitRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginInitRequest) ProtoMessage()               {}
func (*LoginInitRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *LoginInitRequest) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoginInitRequest) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type LoginInitResponse struct {
	Salt      []byte `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	Version   string `protobuf:"bytes,2,opt,name=version" json:"version,omitempty"`
	IsCaptcha bool   `protobuf:"varint,3,opt,name=is_captcha,json=isCaptcha" json:"is_captcha,omitempty"`
	Error     *Error `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *LoginInitResponse) Reset()                    { *m = LoginInitResponse{} }
func (m *LoginInitResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginInitResponse) ProtoMessage()               {}
func (*LoginInitResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *LoginInitResponse) GetSalt() []byte {
	if m != nil {
		return m.Salt
	}
	return nil
}

func (m *LoginInitResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *LoginInitResponse) GetIsCaptcha() bool {
	if m != nil {
		return m.IsCaptcha
	}
	return false
}

func (m *LoginInitResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type LoginAuthRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password []byte `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Captcha  string `protobuf:"bytes,3,opt,name=captcha" json:"captcha,omitempty"`
}

func (m *LoginAuthRequest) Reset()                    { *m = LoginAuthRequest{} }
func (m *LoginAuthRequest) String() string            { return proto.CompactTextString(m) }
func (*LoginAuthRequest) ProtoMessage()               {}
func (*LoginAuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *LoginAuthRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginAuthRequest) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *LoginAuthRequest) GetCaptcha() string {
	if m != nil {
		return m.Captcha
	}
	return ""
}

type LoginAuthResponse struct {
	Msg       string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
	Username  string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Privilege string `protobuf:"bytes,3,opt,name=privilege" json:"privilege,omitempty"`
	Error     *Error `protobuf:"bytes,4,opt,name=error" json:"error,omitempty"`
}

func (m *LoginAuthResponse) Reset()                    { *m = LoginAuthResponse{} }
func (m *LoginAuthResponse) String() string            { return proto.CompactTextString(m) }
func (*LoginAuthResponse) ProtoMessage()               {}
func (*LoginAuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *LoginAuthResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *LoginAuthResponse) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginAuthResponse) GetPrivilege() string {
	if m != nil {
		return m.Privilege
	}
	return ""
}

func (m *LoginAuthResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*LoginInitRequest)(nil), "api.LoginInitRequest")
	proto.RegisterType((*LoginInitResponse)(nil), "api.LoginInitResponse")
	proto.RegisterType((*LoginAuthRequest)(nil), "api.LoginAuthRequest")
	proto.RegisterType((*LoginAuthResponse)(nil), "api.LoginAuthResponse")
}

func init() { proto.RegisterFile("api/login.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 269 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xe9, 0x76, 0xd5, 0xed, 0xb8, 0x60, 0xcd, 0xa9, 0x2c, 0x0a, 0xa5, 0xa7, 0x9e, 0x2a,
	0xe8, 0x5d, 0x10, 0xf1, 0x20, 0x78, 0xca, 0x1f, 0x90, 0xd8, 0x0d, 0xdd, 0x81, 0xb6, 0x89, 0x99,
	0x74, 0x3d, 0xeb, 0x2f, 0x97, 0xa4, 0xe9, 0x5a, 0x14, 0xd9, 0xdb, 0xbc, 0x37, 0xe5, 0xcd, 0xfb,
	0x1a, 0xb8, 0x10, 0x1a, 0x6f, 0x5a, 0xd5, 0x60, 0x5f, 0x69, 0xa3, 0xac, 0x62, 0xb1, 0xd0, 0xb8,
	0x49, 0x9d, 0x5b, 0xab, 0xae, 0x53, 0xc1, 0x2e, 0xee, 0x21, 0x7d, 0x71, 0x5f, 0x3d, 0xf7, 0x68,
	0xb9, 0x7c, 0x1f, 0x24, 0x59, 0x96, 0x42, 0xdc, 0x51, 0x93, 0x45, 0x79, 0x54, 0x26, 0xdc, 0x8d,
	0x2c, 0x83, 0xb3, 0xbd, 0x34, 0x84, 0xaa, 0xcf, 0x16, 0xde, 0x9d, 0x64, 0xf1, 0x15, 0xc1, 0xe5,
	0x2c, 0x80, 0xb4, 0xea, 0x49, 0x32, 0x06, 0x4b, 0x12, 0xad, 0xf5, 0x11, 0x6b, 0xee, 0xe7, 0xff,
	0x33, 0xd8, 0x35, 0x00, 0xd2, 0x6b, 0x2d, 0xb4, 0xad, 0x77, 0x22, 0x8b, 0xf3, 0xa8, 0x5c, 0xf1,
	0x04, 0xe9, 0x71, 0x34, 0x58, 0x0e, 0x27, 0xd2, 0x18, 0x65, 0xb2, 0x65, 0x1e, 0x95, 0xe7, 0xb7,
	0x50, 0x09, 0x8d, 0xd5, 0x93, 0x73, 0xf8, 0xb8, 0x28, 0xb6, 0x01, 0xe2, 0x61, 0xb0, 0xbb, 0x09,
	0x62, 0x03, 0xab, 0x81, 0xa4, 0xe9, 0x45, 0x27, 0x03, 0xc9, 0x41, 0xbb, 0x9d, 0x16, 0x44, 0x1f,
	0xca, 0x6c, 0x7d, 0x97, 0x35, 0x3f, 0x68, 0x57, 0x73, 0xde, 0x24, 0xe1, 0x93, 0x2c, 0x3e, 0x27,
	0xd4, 0xf1, 0x4c, 0x40, 0xfd, 0xfb, 0xb3, 0xe6, 0x97, 0x17, 0xbf, 0x2e, 0x5f, 0x41, 0xa2, 0x0d,
	0xee, 0xb1, 0x95, 0x8d, 0x0c, 0xf9, 0x3f, 0xc6, 0x71, 0xd2, 0xb7, 0x53, 0xff, 0x6a, 0x77, 0xdf,
	0x01, 0x00, 0x00, 0xff, 0xff, 0xe4, 0x1a, 0x04, 0xdc, 0xdf, 0x01, 0x00, 0x00,
}
