// Code generated by protoc-gen-go.
// source: api/register.proto
// DO NOT EDIT!

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// username, golang `^[a-zA-Z][0-9a-zA-Z_]{3,19}$`
// email, golang `^[a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,6}$`
// phone,
// school,
// motto, less than 60 words
type RegisterRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password []byte `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
	Phone    string `protobuf:"bytes,4,opt,name=phone" json:"phone,omitempty"`
	School   string `protobuf:"bytes,5,opt,name=school" json:"school,omitempty"`
	Motto    string `protobuf:"bytes,6,opt,name=motto" json:"motto,omitempty"`
}

func (m *RegisterRequest) Reset()                    { *m = RegisterRequest{} }
func (m *RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*RegisterRequest) ProtoMessage()               {}
func (*RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *RegisterRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisterRequest) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

func (m *RegisterRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *RegisterRequest) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *RegisterRequest) GetSchool() string {
	if m != nil {
		return m.School
	}
	return ""
}

func (m *RegisterRequest) GetMotto() string {
	if m != nil {
		return m.Motto
	}
	return ""
}

// if not empty, something is wrong.
type RegisterResponse struct {
	UserId        int64  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	CheckUsername string `protobuf:"bytes,2,opt,name=check_username,json=checkUsername" json:"check_username,omitempty"`
	CheckPassword string `protobuf:"bytes,3,opt,name=check_password,json=checkPassword" json:"check_password,omitempty"`
	CheckEmail    string `protobuf:"bytes,4,opt,name=check_email,json=checkEmail" json:"check_email,omitempty"`
	CheckPhone    string `protobuf:"bytes,5,opt,name=check_phone,json=checkPhone" json:"check_phone,omitempty"`
	CheckSchool   string `protobuf:"bytes,6,opt,name=check_school,json=checkSchool" json:"check_school,omitempty"`
	CheckMotto    string `protobuf:"bytes,7,opt,name=check_motto,json=checkMotto" json:"check_motto,omitempty"`
	Error         *Error `protobuf:"bytes,8,opt,name=error" json:"error,omitempty"`
}

func (m *RegisterResponse) Reset()                    { *m = RegisterResponse{} }
func (m *RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*RegisterResponse) ProtoMessage()               {}
func (*RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *RegisterResponse) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *RegisterResponse) GetCheckUsername() string {
	if m != nil {
		return m.CheckUsername
	}
	return ""
}

func (m *RegisterResponse) GetCheckPassword() string {
	if m != nil {
		return m.CheckPassword
	}
	return ""
}

func (m *RegisterResponse) GetCheckEmail() string {
	if m != nil {
		return m.CheckEmail
	}
	return ""
}

func (m *RegisterResponse) GetCheckPhone() string {
	if m != nil {
		return m.CheckPhone
	}
	return ""
}

func (m *RegisterResponse) GetCheckSchool() string {
	if m != nil {
		return m.CheckSchool
	}
	return ""
}

func (m *RegisterResponse) GetCheckMotto() string {
	if m != nil {
		return m.CheckMotto
	}
	return ""
}

func (m *RegisterResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*RegisterRequest)(nil), "api.RegisterRequest")
	proto.RegisterType((*RegisterResponse)(nil), "api.RegisterResponse")
}

func init() { proto.RegisterFile("api/register.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 296 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x4c, 0x91, 0x51, 0x4b, 0xf3, 0x30,
	0x14, 0x86, 0xe9, 0xfa, 0xb5, 0xdb, 0x77, 0x36, 0x75, 0x04, 0xd1, 0xb0, 0x1b, 0xeb, 0x40, 0xd8,
	0x55, 0x05, 0xfd, 0x0d, 0xbb, 0xf0, 0x42, 0x18, 0x11, 0xaf, 0x47, 0x6c, 0x83, 0x0d, 0xae, 0x3d,
	0x31, 0xe9, 0xf0, 0xf7, 0x88, 0x7f, 0x54, 0x92, 0xd3, 0xc5, 0x5e, 0xbe, 0xef, 0x79, 0x72, 0x38,
	0x0f, 0x01, 0x26, 0x8d, 0xbe, 0xb7, 0xea, 0x5d, 0xbb, 0x5e, 0xd9, 0xd2, 0x58, 0xec, 0x91, 0xa5,
	0xd2, 0xe8, 0xd5, 0xd2, 0x0f, 0x2a, 0x6c, 0x5b, 0xec, 0xa8, 0x5e, 0xff, 0x24, 0x70, 0x21, 0x06,
	0x52, 0xa8, 0xcf, 0xa3, 0x72, 0x3d, 0x5b, 0xc1, 0xec, 0xe8, 0x94, 0xed, 0x64, 0xab, 0x78, 0x52,
	0x24, 0x9b, 0xff, 0x22, 0x66, 0x3f, 0x33, 0xd2, 0xb9, 0x2f, 0xb4, 0x35, 0x9f, 0x14, 0xc9, 0x66,
	0x21, 0x62, 0x66, 0x97, 0x90, 0xa9, 0x56, 0xea, 0x03, 0x4f, 0xc3, 0x23, 0x0a, 0xbe, 0x35, 0x0d,
	0x76, 0x8a, 0xff, 0xa3, 0x36, 0x04, 0x76, 0x05, 0xb9, 0xab, 0x1a, 0xc4, 0x03, 0xcf, 0x42, 0x3d,
	0x24, 0x4f, 0xb7, 0xd8, 0xf7, 0xc8, 0x73, 0xa2, 0x43, 0x58, 0x7f, 0x4f, 0x60, 0xf9, 0x77, 0xa5,
	0x33, 0xd8, 0x39, 0xc5, 0xae, 0x61, 0xea, 0xcf, 0xda, 0xeb, 0x3a, 0x5c, 0x99, 0x8a, 0xdc, 0xc7,
	0xa7, 0x9a, 0xdd, 0xc1, 0x79, 0xd5, 0xa8, 0xea, 0x63, 0x1f, 0x2d, 0x26, 0x61, 0xd9, 0x59, 0x68,
	0x5f, 0x4f, 0x2a, 0x11, 0x8b, 0x42, 0xe9, 0x08, 0xdb, 0x9d, 0xac, 0x6e, 0x60, 0x4e, 0x18, 0xb9,
	0x91, 0x05, 0x84, 0x6a, 0x1b, 0x04, 0x23, 0x40, 0x9a, 0xd9, 0x08, 0xd8, 0x05, 0xd7, 0x5b, 0x58,
	0x10, 0x30, 0x18, 0x93, 0x1a, 0x3d, 0x7a, 0x21, 0xed, 0xb8, 0x83, 0xe4, 0xa7, 0xa3, 0x1d, 0xcf,
	0xbe, 0x61, 0x05, 0x64, 0xca, 0x5a, 0xb4, 0x7c, 0x56, 0x24, 0x9b, 0xf9, 0x03, 0x94, 0xd2, 0xe8,
	0x72, 0xeb, 0x1b, 0x41, 0x83, 0xb7, 0x3c, 0x7c, 0xe8, 0xe3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x14, 0xc0, 0x79, 0xfa, 0xfd, 0x01, 0x00, 0x00,
}
